# Copyright (c) 2026 FoBE Studio
# SPDX-License-Identifier: Apache-2.0

add_subdirectory_ifdef(CONFIG_IMG_MANAGER dfu)
if(CONFIG_MBS)
	add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../cmake/protobuf
		${APPLICATION_BINARY_DIR}/generated)
	add_subdirectory(settings)
	add_subdirectory(mgmt)
	add_subdirectory(shell)
	add_subdirectory(bluetooth)
	add_subdirectory(display)
	add_subdirectory(clock)
	add_subdirectory(radio)
	add_subdirectory(indicator)
	add_subdirectory(power)
	add_subdirectory(gnss)
	add_subdirectory(input)
	add_subdirectory(telemetry)
	add_subdirectory(contact)
	add_subdirectory(channel)
	add_subdirectory(fs)
	add_subdirectory(meshcore)
	add_subdirectory(management)
	add_subdirectory(firmware)
	add_subdirectory(notify)
	add_subdirectory(message)
	add_subdirectory(llext)
	add_subdirectory(desktop)
endif()
add_subdirectory_ifdef(CONFIG_U8G2 u8g2)
add_subdirectory_ifdef(CONFIG_ZUI zui)
