/* SPDX-License-Identifier: Apache-2.0 */

/*
 * Copyright (c) 2026 FoBE Studio
 */

/**
 * @file
 * @brief Meshbus Desktop app loading and service bridge API
 *
 * This module provides path-based APIs for Desktop to inspect and run `.mba` app
 * extensions from `/extra/apps`.
 */

#ifndef ZEPHYR_INCLUDE_MESHBUS_LLEXT_H_
#define ZEPHYR_INCLUDE_MESHBUS_LLEXT_H_

#include <stddef.h>
#include <stdint.h>

#include <zephyr/kernel.h>
#include <zephyr/toolchain.h>
#include <zephyr/zbus/zbus.h>

#include <meshbus_llext_metadata_version.h>

#include "meshbus/llext.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Maximum LLEXT ID length (without trailing NUL). */
#define MESHBUS_LLEXT_ID_MAX_LEN 31
/** Maximum LLEXT version string length (without trailing NUL). */
#define MESHBUS_LLEXT_VERSION_MAX_LEN 15
/** Maximum stored filesystem path length (without trailing NUL). */
#define MESHBUS_LLEXT_PATH_MAX_LEN 191
/** Maximum app display name length (without trailing NUL). */
#define MESHBUS_LLEXT_NAME_MAX_LEN 63
/** Maximum app symbol name length (without trailing NUL). */
#define MESHBUS_LLEXT_SYMBOL_MAX_LEN 63
/** Maximum target string length (without trailing NUL). */
#define MESHBUS_LLEXT_TARGET_MAX_LEN 63
/** Filesystem suffix for Meshbus LLEXT Desktop app artifacts. */
#define MESHBUS_LLEXT_APP_SUFFIX ".mba"
/** Default filesystem directory for Meshbus LLEXT Desktop app artifacts. */
#define MESHBUS_LLEXT_APP_DEFAULT_PATH "/extra/apps"

/** Section name for LLEXT metadata blobs in `.mba` ELF files. */
#define MESHBUS_LLEXT_METADATA_SECTION ".meshbus.llext.meta"
/** Section name for app metadata blob in `.mba` ELF files. */
#define MESHBUS_LLEXT_APP_METADATA_SECTION MESHBUS_LLEXT_METADATA_SECTION
/** Magic value for @ref meshbus_llext_app_metadata. */
#define MESHBUS_LLEXT_APP_METADATA_MAGIC 0x4D424C41U
/** Supported app metadata structure version. */
#define MESHBUS_LLEXT_APP_METADATA_VERSION MESHBUS_LLEXT_METADATA_VERSION
/** Size of @ref meshbus_llext_app_metadata on the wire. */
#define MESHBUS_LLEXT_APP_METADATA_SIZE 368U
/** Fixed app icon width in pixels. */
#define MESHBUS_LLEXT_APP_ICON_WIDTH 10U
/** Fixed app icon height in pixels. */
#define MESHBUS_LLEXT_APP_ICON_HEIGHT 10U
/** Exact fixed 10x10 raw mono app icon payload size, in bytes. */
#define MESHBUS_LLEXT_APP_ICON_DATA_SIZE \
	(((MESHBUS_LLEXT_APP_ICON_WIDTH + 7U) / 8U) * MESHBUS_LLEXT_APP_ICON_HEIGHT)
/** Maximum fixed 10x10 raw mono app icon payload length, in bytes. */
#define MESHBUS_LLEXT_APP_ICON_DATA_MAX_LEN MESHBUS_LLEXT_APP_ICON_DATA_SIZE

/**
 * @brief Desktop app metadata descriptor stored in
 *        @ref MESHBUS_LLEXT_APP_METADATA_SECTION.
 *
 * `edk_version`, `target`, `heap_size`, and `icon_data` are generated by build
 * tooling. App authors must not hand-write those fields in source YAML. Icons
 * are always fixed 10x10 raw mono bitmap payloads, with
 * one byte per 8-pixel row chunk. Empty `icon_data_size` means the Desktop
 * launcher should use its default LLEXT app icon.
 */
struct meshbus_llext_app_metadata {
	uint32_t magic;
	uint32_t metadata_version;
	uint32_t size;
	uint32_t stack_size;
	uint32_t heap_size;
	uint32_t icon_data_size;
	char id[MESHBUS_LLEXT_ID_MAX_LEN + 1];
	char name[MESHBUS_LLEXT_NAME_MAX_LEN + 1];
	char app_version[MESHBUS_LLEXT_VERSION_MAX_LEN + 1];
	char entry_point_symbol[MESHBUS_LLEXT_SYMBOL_MAX_LEN + 1];
	char edk_version[MESHBUS_LLEXT_VERSION_MAX_LEN + 1];
	uint8_t compatibility_reserved[48];
	char target[MESHBUS_LLEXT_TARGET_MAX_LEN + 1];
	uint8_t icon_data[MESHBUS_LLEXT_APP_ICON_DATA_MAX_LEN];
	uint8_t reserved[20];
};

BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, id) == 24U,
	     "meshbus LLEXT app metadata id offset changed");
BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, entry_point_symbol) == 136U,
	     "meshbus LLEXT app metadata entry offset changed");
BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, edk_version) == 200U,
	     "meshbus LLEXT app metadata EDK version offset changed");
BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, compatibility_reserved) == 216U,
	     "meshbus LLEXT app metadata compatibility reserved offset changed");
BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, target) == 264U,
	     "meshbus LLEXT app metadata target offset changed");
BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, icon_data) == 328U,
	     "meshbus LLEXT app metadata icon offset changed");
BUILD_ASSERT(offsetof(struct meshbus_llext_app_metadata, reserved) == 348U,
	     "meshbus LLEXT app metadata reserved offset changed");
BUILD_ASSERT(sizeof(struct meshbus_llext_app_metadata) ==
	     MESHBUS_LLEXT_APP_METADATA_SIZE,
	     "meshbus LLEXT app metadata layout changed");

/** @brief Attribute for placing app metadata into the LLEXT metadata section. */
#define MESHBUS_LLEXT_APP_METADATA_ATTR \
	Z_GENERIC_SECTION(MESHBUS_LLEXT_APP_METADATA_SECTION) __used

/** @brief Desktop app entry function type resolved from a loaded `.mba`. */
typedef void (*meshbus_llext_app_entry_t)(void *args);

/** @brief Opaque loaded Desktop app LLEXT session. */
struct meshbus_llext_app_session;

/** @brief Desktop app metadata snapshot returned by probe/load APIs. */
struct meshbus_llext_app_info {
	char id[MESHBUS_LLEXT_ID_MAX_LEN + 1];
	char name[MESHBUS_LLEXT_NAME_MAX_LEN + 1];
	char version[MESHBUS_LLEXT_VERSION_MAX_LEN + 1];
	char path[MESHBUS_LLEXT_PATH_MAX_LEN + 1];
	char entry_point_symbol[MESHBUS_LLEXT_SYMBOL_MAX_LEN + 1];
	char edk_version[MESHBUS_LLEXT_VERSION_MAX_LEN + 1];
	char target[MESHBUS_LLEXT_TARGET_MAX_LEN + 1];
	uint32_t stack_size;
	uint32_t heap_size;
	uint32_t icon_data_size;
	uint8_t icon_data[MESHBUS_LLEXT_APP_ICON_DATA_MAX_LEN];
	int32_t last_error;
};

/** @brief LLEXT bridge wake event bit posted to subscriber @ref k_event. */
#define MESHBUS_LLEXT_ZBUS_EVT_PENDING (1U << 31)

/** @brief Unified Meshbus ZBus channel IDs for LLEXT bridge APIs. */
enum meshbus_llext_zbus_channel {
	MESHBUS_LLEXT_ZBUS_INPUT_KEY_CHAN = 0,
	MESHBUS_LLEXT_ZBUS_INPUT_ACTION_CHAN = 1,
	MESHBUS_LLEXT_ZBUS_NOTIFY_CHAN = 2,
	MESHBUS_LLEXT_ZBUS_BLUETOOTH_PAIRING_CHAN = 3,
	MESHBUS_LLEXT_ZBUS_BLUETOOTH_STATE_CHAN = 4,
	MESHBUS_LLEXT_ZBUS_DISPLAY_STATE_CHAN = 5,
	MESHBUS_LLEXT_ZBUS_GNSS_DATA_CHAN = 6,
	MESHBUS_LLEXT_ZBUS_MESSAGE_SEND_TO_NODE_REQUEST_CHAN = 8,
	MESHBUS_LLEXT_ZBUS_MESSAGE_SEND_TO_CHANNEL_REQUEST_CHAN = 9,
	MESHBUS_LLEXT_ZBUS_MESSAGE_RESPONSE_CHAN = 10,
	MESHBUS_LLEXT_ZBUS_MESSAGE_ACK_RESPONSE_CHAN = 11,
	MESHBUS_LLEXT_ZBUS_MESSAGE_RECEIVED_CHAN = 12,
	MESHBUS_LLEXT_ZBUS_MESHCORE_ADVERT_REQUEST_CHAN = 14,
	MESHBUS_LLEXT_ZBUS_CONTACT_SHARE_REQUEST_CHAN = 15,
	MESHBUS_LLEXT_ZBUS_CONTACT_DISCOVER_PATH_REQUEST_CHAN = 16,
	MESHBUS_LLEXT_ZBUS_CONTACT_TRACE_PATH_REQUEST_CHAN = 17,
	MESHBUS_LLEXT_ZBUS_CONTACT_TELEMETRY_REQUEST_CHAN = 18,
	MESHBUS_LLEXT_ZBUS_CONTACT_ADVERT_RESPONSE_CHAN = 19,
	MESHBUS_LLEXT_ZBUS_CONTACT_PATH_RESPONSE_CHAN = 20,
	MESHBUS_LLEXT_ZBUS_CONTACT_TRACE_PATH_RESPONSE_CHAN = 21,
	MESHBUS_LLEXT_ZBUS_CONTACT_TELEMETRY_RESPONSE_CHAN = 22,
	MESHBUS_LLEXT_ZBUS_POWER_FUEL_GAUGE_DATA_CHAN = 23,
	MESHBUS_LLEXT_ZBUS_RADIO_RECEIVE_CHAN = 24,
	MESHBUS_LLEXT_ZBUS_RADIO_PUBLISH_CHAN = 25,
	MESHBUS_LLEXT_ZBUS_TELEMETRY_DATA_CHAN = 26,
	MESHBUS_LLEXT_ZBUS_INDICATOR_LIGHT_PLAY_CHAN = 27,
	MESHBUS_LLEXT_ZBUS_INDICATOR_BUZZER_PLAY_CHAN = 28,
	MESHBUS_LLEXT_ZBUS_RADIO_TX_DONE_CHAN = 29,
	MESHBUS_LLEXT_ZBUS_RADIO_STATE_CHAN = 30,
	MESHBUS_LLEXT_ZBUS_MESHCORE_NODE_DISCOVER_REQUEST_CHAN = 31,
	MESHBUS_LLEXT_ZBUS_CONTACT_DISCOVER_RESPONSE_CHAN = 32,
	MESHBUS_LLEXT_ZBUS_RADIO_CW_CHAN = 33,
	MESHBUS_LLEXT_ZBUS_RADIO_CW_DONE_CHAN = 34,
	MESHBUS_LLEXT_ZBUS_CHANNEL_COUNT,
};

BUILD_ASSERT(MESHBUS_LLEXT_ZBUS_CHANNEL_COUNT <= 64,
	     "meshbus LLEXT ZBus bridge bit masks support at most 64 channels");

/** @brief Convert one LLEXT ZBus channel ID to a subscription/pending bit. */
#define MESHBUS_LLEXT_ZBUS_CH_BIT(channel) (UINT64_C(1) << (channel))

/** @brief LLEXT runtime configuration (maps to meshbus_LlextConfig). */
typedef meshbus_LlextConfig meshbus_llext_config;

/**
 * @brief Copy the current LLEXT application configuration.
 *
 * @param cfg Output configuration snapshot.
 *
 * @retval 0 on success.
 * @retval -EINVAL if @p cfg is NULL.
 */
int meshbus_llext_config_get(meshbus_llext_config *cfg);

/**
 * @brief Apply and persist the LLEXT application configuration.
 *
 * When `enabled` is false, new Desktop app probe/load requests are rejected.
 * Changing configuration does not interrupt an already loaded application.
 *
 * @param cfg Configuration to apply.
 *
 * @retval 0 on success.
 * @retval -EINVAL if @p cfg is NULL or contains an invalid value.
 */
int meshbus_llext_config_set(const meshbus_llext_config *cfg);

/**
 * @brief Reset LLEXT application configuration to defaults.
 *
 * Resetting configuration does not interrupt an already loaded application.
 *
 * @retval 0 on success.
 * @retval negative errno on settings delete failure.
 */
int meshbus_llext_config_reset(void);

/**
 * @brief Return whether any LLEXT runtime resource is active.
 *
 * Filesystem lifecycle code uses this as a conservative busy gate before
 * destructive storage operations such as formatting the extension volume.
 *
 * @retval true if a Desktop app session is active.
 * @retval false if no LLEXT runtime object is active.
 */
bool meshbus_llext_runtime_busy(void);

/**
 * @brief Read and validate `.mba` app metadata without loading the extension.
 *
 * Probe is metadata-only and does not reserve LLEXT heap. The exact target
 * must match the running firmware for probe to succeed. The EDK version is
 * provenance only and is not a compatibility gate. Probe is rejected when
 * LLEXT is disabled by configuration.
 *
 * @param path Full filesystem path to a `.mba` file.
 * @param info Output metadata snapshot.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments are invalid.
 * @retval -ENODEV if LLEXT is disabled by configuration.
 * @retval -ENOEXEC if metadata is malformed.
 * @retval -EPROTONOSUPPORT if the metadata version is unsupported.
 * @retval -EXDEV if the package target differs from the host target.
 * @retval negative errno from filesystem access.
 */
int meshbus_llext_app_probe(const char *path, struct meshbus_llext_app_info *info);

/**
 * @brief Load one selected `.mba` app and prepare its entry symbol.
 *
 * Load re-reads metadata and is authoritative even if a previous probe
 * succeeded. Only one app session can be loaded at a time. Load is rejected
 * when LLEXT is disabled by configuration.
 *
 * @param path Full filesystem path to a `.mba` file.
 * @param session_out Output app session handle. On failure this is normally
 *                    NULL. If failure cleanup also fails, a non-NULL handle
 *                    retains the partial resources; the caller must keep it
 *                    and retry meshbus_llext_app_unload() before loading again.
 *                    Such a session has no callable app entry.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments are invalid.
 * @retval -ENODEV if LLEXT is disabled by configuration.
 * @retval -EBUSY if another app session is loaded or loading.
 * @retval -E2BIG if the app heap estimate exceeds the configured app budget.
 * @retval -ENOEXEC if metadata, bring-up, or entry resolution fails.
 * @retval negative errno from filesystem, Zephyr LLEXT loading, or failure cleanup.
 */
int meshbus_llext_app_load(const char *path,
			   struct meshbus_llext_app_session **session_out);

/**
 * @brief Copy metadata for a loaded app session.
 *
 * @param session Loaded app session.
 * @param info Output app metadata snapshot.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments are invalid.
 * @retval -ENOENT if @p session is not a loaded app session.
 */
int meshbus_llext_app_get_info(const struct meshbus_llext_app_session *session,
			       struct meshbus_llext_app_info *info);

/**
 * @brief Return the typed Desktop app entry for a loaded app session.
 *
 * The entry is unavailable once unloading begins, including when reclamation
 * fails and the session is retained for a later retry.
 *
 * @param session Loaded app session.
 * @param entry_out Output Desktop-compatible blocking entry function.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments are invalid.
 * @retval -ENOENT if @p session has no executable app entry.
 */
int meshbus_llext_app_get_entry(const struct meshbus_llext_app_session *session,
				meshbus_llext_app_entry_t *entry_out);

/**
 * @brief Unload a loaded app session after its entry has returned.
 *
 * The caller must ensure no app-owned callbacks, work items, timers, or ZBus
 * observers can still call into extension code.
 * On failure the session remains owned by the caller and blocks new loads;
 * keep the handle and retry unloading. This also reclaims a partial session
 * returned when load failure cleanup could not finish.
 *
 * @param session Loaded app session.
 *
 * @retval 0 on success.
 * @retval -EINVAL if @p session is NULL.
 * @retval -ENOENT if @p session is not currently loaded.
 * @retval -EBUSY if unload is already in progress.
 * @retval negative errno from LLEXT teardown/unload.
 */
int meshbus_llext_app_unload(struct meshbus_llext_app_session *session);

/**
 * @brief Subscribe a service event object to Meshbus ZBus bridge channels.
 *
 * The caller owns @p evt and must keep it valid until unsubscribed or until the
 * service exits. @p channel_mask uses @ref MESHBUS_LLEXT_ZBUS_CH_BIT.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments or channel bits are invalid.
 * @retval -ENODEV if no bridge channels are available.
 * @retval -ENOMEM if the subscriber table is full.
 */
int meshbus_llext_zbus_subscribe(struct k_event *evt, uint64_t channel_mask);

/**
 * @brief Remove a previous LLEXT ZBus bridge subscription.
 *
 * @retval 0 on success.
 * @retval -EINVAL if @p evt is NULL.
 * @retval -ENOENT if @p evt is not subscribed.
 */
int meshbus_llext_zbus_unsubscribe(struct k_event *evt);

/**
 * @brief Take pending bridge channels for a subscribed event object.
 *
 * The returned mask is cleared from the subscription. A subscriber should call
 * this after waiting for @ref MESHBUS_LLEXT_ZBUS_EVT_PENDING on @p evt.
 *
 * @param evt Subscribed event object.
 * @param pending_mask Output channel bit mask.
 *
 * @retval 0 if one or more channel bits were returned.
 * @retval -EINVAL if arguments are invalid.
 * @retval -ENOENT if @p evt is not subscribed.
 * @retval -ENOMSG if no channel is pending.
 */
int meshbus_llext_zbus_take_pending(struct k_event *evt, uint64_t *pending_mask);

/**
 * @brief Read the latest message from a bridged Meshbus ZBus channel.
 *
 * @param channel LLEXT bridge channel id.
 * @param msg Output message buffer.
 * @param msg_size Size of @p msg. Must exactly match the channel payload type.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments are invalid or @p msg_size does not match.
 * @retval -ENODEV if the channel is not available in this firmware build.
 * @retval negative errno from zbus_chan_read().
 */
int meshbus_llext_zbus_read(enum meshbus_llext_zbus_channel channel, void *msg, size_t msg_size);

/**
 * @brief Publish a message to a bridged Meshbus ZBus channel.
 *
 * Applications can publish to the channels permitted by the bridge.
 * @p msg_size must exactly match the channel payload type.
 *
 * @retval 0 on success.
 * @retval -EINVAL if arguments are invalid or @p msg_size does not match.
 * @retval -ENODEV if the channel is not available in this firmware build.
 * @retval -ENOTSUP if publishing is not allowed for @p channel.
 * @retval negative errno from zbus_chan_pub().
 */
int meshbus_llext_zbus_publish(enum meshbus_llext_zbus_channel channel, const void *msg,
			       size_t msg_size);

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_MESHBUS_LLEXT_H_ */
