/*
 * Copyright (c) 2026 FoBE Studio
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Meshbus protocol-agnostic remote management transport contract
 */

#ifndef ZEPHYR_INCLUDE_MESHBUS_MANAGEMENT_H_
#define ZEPHYR_INCLUDE_MESHBUS_MANAGEMENT_H_

#include <stddef.h>
#include <stdint.h>

#include <zephyr/sys/util.h>
#include <zephyr/zbus/zbus.h>

#include "meshbus/management.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MESHBUS_MANAGEMENT_MAGIC0 0xA5U
#define MESHBUS_MANAGEMENT_MAGIC1 0x4DU
#define MESHBUS_MANAGEMENT_VERSION 2U
#define MESHBUS_MANAGEMENT_TARGET_ID_SIZE 8U
#define MESHBUS_MANAGEMENT_NONCE_SIZE 16U
#define MESHBUS_MANAGEMENT_SESSION_KEY_SIZE 16U
#define MESHBUS_MANAGEMENT_AEAD_NONCE_SIZE 12U
#define MESHBUS_MANAGEMENT_AEAD_TAG_SIZE 8U
#define MESHBUS_MANAGEMENT_HEADER_SIZE 24U
/** Fixed route-binding fields following the client nonce in SESSION_INIT. */
#define MESHBUS_MANAGEMENT_SESSION_ROUTE_HEADER_SIZE 3U
/** SESSION_INIT flag indicating an authenticated explicit return route. */
#define MESHBUS_MANAGEMENT_SESSION_ROUTE_PRESENT BIT(0)
/** Minimum length of a provisioned management password, in ASCII bytes. */
#define MESHBUS_MANAGEMENT_SECRET_MIN_LEN 8U
/** Maximum length of a provisioned management password, in ASCII bytes. */
#define MESHBUS_MANAGEMENT_SECRET_MAX_LEN 16U
#define MESHBUS_MANAGEMENT_FRAME_MAX_LEN 184U
#define MESHBUS_MANAGEMENT_SMP_PACKET_MAX_LEN 608U
#define MESHBUS_MANAGEMENT_SMP_RESPONSE_MAX_LEN 608U
#if defined(CONFIG_MESHBUS_CONTACT_PREFIX_BYTES)
#define MESHBUS_MANAGEMENT_CONTACT_PREFIX_BYTES CONFIG_MESHBUS_CONTACT_PREFIX_BYTES
#else
#define MESHBUS_MANAGEMENT_CONTACT_PREFIX_BYTES 4U
#endif

enum meshbus_management_frame_type {
	MESHBUS_MANAGEMENT_FRAME_TYPE_SESSION_INIT = 1U,
	MESHBUS_MANAGEMENT_FRAME_TYPE_SESSION_CHALLENGE = 2U,
	MESHBUS_MANAGEMENT_FRAME_TYPE_DATA_REQUEST = 3U,
	MESHBUS_MANAGEMENT_FRAME_TYPE_DATA_RESPONSE = 4U,
	/** Unencrypted failure for a pending, stale, or busy session. */
	MESHBUS_MANAGEMENT_FRAME_TYPE_SESSION_REJECT = 5U,
	/** Authenticated acknowledgement for a non-final request fragment. */
	MESHBUS_MANAGEMENT_FRAME_TYPE_DATA_REQUEST_ACK = 6U,
	/** Authenticated acknowledgement for a non-final response fragment. */
	MESHBUS_MANAGEMENT_FRAME_TYPE_DATA_RESPONSE_ACK = 7U,
};

/**
 * @brief Management configuration persisted as the service settings blob.
 *
 * An empty secret means the endpoint is unprovisioned and rejects remote
 * session initialization. A provisioned value contains 8 to 16 printable
 * non-whitespace ASCII bytes; product-facing clients call it a management
 * password.
 */
typedef meshbus_ManagementConfig meshbus_management_config;

/** @brief Authenticated remote SMP exchange request. */
typedef struct meshbus_management_smp_request_event {
	/** Contact public-key prefix selecting the remote target. */
	uint8_t contact_prefix[MESHBUS_MANAGEMENT_CONTACT_PREFIX_BYTES];
	/**
	 * Valid bytes in @ref packet.
	 *
	 * This must not exceed @ref meshbus_management_smp_effective_max_len_get.
	 */
	uint16_t packet_len;
	/**
	 * Complete SMP request packet, including the 8-byte SMP header.
	 *
	 * The array size is the public ABI storage ceiling. The configured bearer
	 * may support a smaller effective packet size.
	 */
	uint8_t packet[MESHBUS_MANAGEMENT_SMP_PACKET_MAX_LEN];
} meshbus_management_smp_request_event;

/** @brief Authenticated management password rotation request. */
typedef struct meshbus_management_secret_set_request_event {
	/** Contact public-key prefix selecting the remote target. */
	uint8_t contact_prefix[MESHBUS_MANAGEMENT_CONTACT_PREFIX_BYTES];
	/** Valid bytes in @ref secret (8 to 16 printable ASCII bytes). */
	uint8_t secret_len;
	/** Replacement management-password bytes. */
	uint8_t secret[MESHBUS_MANAGEMENT_SECRET_MAX_LEN];
} meshbus_management_secret_set_request_event;

/** @brief Remote SMP response observed asynchronously. */
typedef struct meshbus_management_smp_response_event {
	/** Request correlation tag generated by the initiating request. */
	uint32_t tag;
	/**
	 * Final exchange status.
	 *
	 * A value of 0 means @ref response contains a complete SMP response.
	 * Negative errno values distinguish timeout, transport, authentication,
	 * and protocol failures.
	 */
	int32_t status;
	/**
	 * Valid bytes in @ref response.
	 *
	 * A value of 0 accompanies a negative @ref status.
	 */
	uint16_t response_len;
	/**
	 * Complete remote SMP response packet.
	 *
	 * The array size is the public ABI storage ceiling. Responses are limited
	 * to @ref meshbus_management_smp_effective_max_len_get in this build.
	 */
	uint8_t response[MESHBUS_MANAGEMENT_SMP_RESPONSE_MAX_LEN];
} meshbus_management_smp_response_event;

ZBUS_CHAN_DECLARE(meshbus_management_smp_response_chan);

/**
 * @brief Get the current persisted management configuration.
 *
 * @param cfg Output parameter for current configuration.
 * @return 0 on success, negative errno on failure.
 */
int meshbus_management_config_get(meshbus_management_config *cfg);

/**
 * @brief Set the current persisted management configuration.
 *
 * Validates, applies, and schedules persistence. If @ref secret is omitted,
 * the current secret is preserved. A non-empty value must contain 8 to 16
 * printable non-whitespace ASCII bytes.
 *
 * @param cfg New configuration.
 * @return 0 on success, negative errno on failure.
 */
int meshbus_management_config_set(const meshbus_management_config *cfg);

/**
 * @brief Reset management configuration to the unprovisioned state.
 *
 * Deletes the persisted secret. Remote session initialization remains disabled
 * until a new secret is configured through a trusted local path.
 *
 * @return 0 on success, negative errno on failure.
 */
int meshbus_management_config_reset(void);

/**
 * @brief Get the effective remote SMP packet capacity for this build.
 *
 * The returned value is the common request and response limit after applying
 * the configured management frame size, fragment count, MCUmgr transport
 * buffer size, and public ABI storage ceilings.
 *
 * @return Maximum accepted remote SMP request or response length in bytes.
 */
size_t meshbus_management_smp_effective_max_len_get(void);

/**
 * @brief Start an authenticated remote SMP exchange for a stored Contact.
 *
 * The local device resolves the target public key, route metadata, and
 * management secret from the Contact record. The request returns after the
 * first LoRa request is queued. The final remote SMP response is published on
 * @ref meshbus_management_smp_response_chan.
 *
 * @param request SMP exchange request.
 * @param out_tag Optional generated request correlation tag.
 * @return 0 on success, negative errno on failure.
 * @retval -EMSGSIZE The packet exceeds the effective capacity for this build.
 */
int meshbus_management_smp_request(
	const meshbus_management_smp_request_event *request, uint32_t *out_tag);

/**
 * @brief Start an authenticated remote SMP exchange with a transient secret.
 *
 * This variant resolves the target public key and route metadata from the
 * Contact record selected by
 * @ref meshbus_management_smp_request_event.contact_prefix, but authenticates
 * the exchange with caller-supplied secret bytes instead of the Contact's
 * persisted management secret. The supplied secret is never persisted by the
 * management service.
 *
 * @param request SMP exchange request.
 * @param secret Transient management secret bytes.
 * @param secret_len Valid bytes in @p secret.
 * @param out_tag Optional generated request correlation tag.
 * @return 0 on success, negative errno on failure.
 * @retval -EMSGSIZE The packet exceeds the effective capacity for this build.
 */
int meshbus_management_smp_request_with_secret(
	const meshbus_management_smp_request_event *request,
	const uint8_t *secret, size_t secret_len, uint32_t *out_tag);

/**
 * @brief Rotate a stored Contact's management password.
 *
 * The local device authenticates with the Contact's current management secret,
 * sends a management credential write carrying the replacement password,
 * and returns after the first LoRa request is queued. The final remote SMP
 * response is published on @ref meshbus_management_smp_response_chan.
 *
 * @param request Secret rotation request.
 * @param out_tag Optional generated request correlation tag.
 * @return 0 on success, negative errno on failure.
 */
int meshbus_management_secret_set_request(
	const meshbus_management_secret_set_request_event *request, uint32_t *out_tag);

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_MESHBUS_MANAGEMENT_H_ */
