/* SPDX-FileCopyrightText: FoBE Studio */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const char DESKTOP_TEXT_APP_BUILD_WARNING_TITLE[];
extern const char DESKTOP_TEXT_APP_BUILD_WARNING[];

/* Common desktop text */
extern const char DESKTOP_TEXT_COMMON_OFF[];
extern const char DESKTOP_TEXT_COMMON_ON[];
extern const char DESKTOP_TEXT_COMMON_NO[];
extern const char DESKTOP_TEXT_COMMON_YES[];
extern const char *const DESKTOP_TEXT_COMMON_BOOL_VALUES[2];
extern const char *const DESKTOP_TEXT_COMMON_NO_YES_VALUES[2];
extern const char DESKTOP_TEXT_COMMON_SETTINGS_APPLIED[];
extern const char DESKTOP_TEXT_COMMON_SETTINGS_RESET[];
extern const char DESKTOP_TEXT_COMMON_SETTINGS_INVALID[];
extern const char DESKTOP_TEXT_COMMON_ACTION_APPLY[];
extern const char DESKTOP_TEXT_COMMON_ACTION_RESET[];
extern const char DESKTOP_TEXT_COMMON_BUTTON_CLEAR[];
extern const char DESKTOP_TEXT_COMMON_BUTTON_START[];
extern const char DESKTOP_TEXT_COMMON_BUTTON_STOP[];
extern const char DESKTOP_TEXT_COMMON_NO_DATA[];
extern const char DESKTOP_TEXT_COMMON_NONE[];
extern const char DESKTOP_TEXT_COMMON_UNKNOWN[];
extern const char DESKTOP_TEXT_COMMON_OK[];
extern const char DESKTOP_TEXT_COMMON_RESET[];
extern const char DESKTOP_TEXT_COMMON_APPLY[];
extern const char DESKTOP_TEXT_COMMON_CANCEL[];
extern const char DESKTOP_TEXT_COMMON_REFRESH[];
extern const char DESKTOP_TEXT_COMMON_MENU_SETTINGS[];
extern const char DESKTOP_TEXT_COMMON_MENU_STATS[];
extern const char DESKTOP_TEXT_COMMON_BUTTON_REPLY[];
extern const char DESKTOP_TEXT_COMMON_EMPTY[];
extern const char DESKTOP_TEXT_COMMON_ROUTE[];
extern const char DESKTOP_TEXT_COMMON_NOT_AVAILABLE[];
extern const char DESKTOP_TEXT_COMMON_UNKNOWN_WORD[];
extern const char DESKTOP_TEXT_COMMON_YES_LOWER[];
extern const char DESKTOP_TEXT_COMMON_NO_LOWER[];
extern const char DESKTOP_TEXT_COMMON_RESET_CONFIRM_TEXT[];

/* Other apps text */
extern const char DESKTOP_TEXT_BLUETOOTH_TITLE[];
extern const char DESKTOP_TEXT_CLOCK_TITLE[];
extern const char DESKTOP_TEXT_DISPLAY_TITLE[];
extern const char DESKTOP_TEXT_GNSS_TITLE[];
extern const char DESKTOP_TEXT_LAUNCHER_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_TITLE[];
extern const char DESKTOP_TEXT_MESSAGES_TITLE[];
extern const char DESKTOP_TEXT_NODES_TITLE[];
extern const char DESKTOP_TEXT_POWER_TITLE[];
extern const char DESKTOP_TEXT_SYSTEM_TITLE[];
extern const char DESKTOP_TEXT_TELEMETRY_TITLE[];

/* Bluetooth app text */
extern const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_ENABLED[];
extern const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_MESHCORE_COMPANION[];
extern const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_PASSKEY_MODE[];
extern const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_FIXED_PASSKEY[];
#define DESKTOP_TEXT_BLUETOOTH_PASSKEY_MODE_COUNT 2U
extern const char *const DESKTOP_TEXT_BLUETOOTH_PASSKEY_MODE_VALUES[DESKTOP_TEXT_BLUETOOTH_PASSKEY_MODE_COUNT];

/* Notify text */
extern const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_PAIRING_HEADER[];
extern const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_CONNECTED[];
extern const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_DISCONNECTED[];
extern const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_PAIRING_CODE_FORMAT[];

/* Clock app text */
extern const char DESKTOP_TEXT_CLOCK_SETTINGS_FORMAT[];
extern const char DESKTOP_TEXT_CLOCK_SETTINGS_UTC_OFFSET[];
extern const char DESKTOP_TEXT_CLOCK_UTC_OFFSET_FORMAT[];
#define DESKTOP_TEXT_CLOCK_FORMAT_COUNT 2U
extern const char *const DESKTOP_TEXT_CLOCK_FORMAT_VALUES[DESKTOP_TEXT_CLOCK_FORMAT_COUNT];

/* Display app text */
extern const char DESKTOP_TEXT_DISPLAY_SETTINGS_BRIGHTNESS[];
extern const char DESKTOP_TEXT_DISPLAY_SETTINGS_SLEEP_TIMEOUT[];
extern const char DESKTOP_TEXT_DISPLAY_SETTINGS_INVERT[];
extern const char DESKTOP_TEXT_DISPLAY_NEVER[];

/* GNSS app text */
extern const char DESKTOP_TEXT_GNSS_STATUS[];
extern const char DESKTOP_TEXT_GNSS_STATUS_TITLE[];
extern const char DESKTOP_TEXT_GNSS_SATELLITES[];
extern const char DESKTOP_TEXT_GNSS_ACQUISITION[];
extern const char DESKTOP_TEXT_GNSS_ACTION_RELOAD[];
extern const char DESKTOP_TEXT_GNSS_NO_SATELLITES_PAREN[];
extern const char DESKTOP_TEXT_GNSS_STATUS_LOADING[];
extern const char DESKTOP_TEXT_GNSS_SATELLITE[];
extern const char DESKTOP_TEXT_GNSS_NO_SATELLITE_SELECTED[];
extern const char DESKTOP_TEXT_GNSS_SATELLITE_DETAIL_FORMAT[];
extern const char DESKTOP_TEXT_GNSS_STATUS_DETAIL_FORMAT[];
extern const char DESKTOP_TEXT_GNSS_NOT_AVAILABLE[];
extern const char DESKTOP_TEXT_GNSS_UNIT_DEG[];
extern const char DESKTOP_TEXT_GNSS_UNIT_M[];
extern const char DESKTOP_TEXT_GNSS_UNIT_MPS[];
extern const char DESKTOP_TEXT_GNSS_STATE_SLEEP[];
extern const char DESKTOP_TEXT_GNSS_STATE_ACQUIRING[];
extern const char DESKTOP_TEXT_GNSS_STATE_TRACK[];
extern const char DESKTOP_TEXT_GNSS_STATE_ERROR[];
extern const char DESKTOP_TEXT_GNSS_FIX_NO_FIX[];
extern const char DESKTOP_TEXT_GNSS_FIX_GNSS_FIX[];
extern const char DESKTOP_TEXT_GNSS_FIX_DGNSS_FIX[];
extern const char DESKTOP_TEXT_GNSS_FIX_ESTIMATED_FIX[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_INVALID[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_GNSS_SPS[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_DGNSS[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_GNSS_PPS[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_RTK[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_FLOAT_RTK[];
extern const char DESKTOP_TEXT_GNSS_QUALITY_ESTIMATED[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_GPS_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_GLONASS_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_GALILEO_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_BEIDOU_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_QZSS_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_IRNSS_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_SBAS_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_IMES_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_UNKNOWN_SHORT[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_GPS_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_GLONASS_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_GALILEO_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_BEIDOU_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_QZSS_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_IRNSS_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_SBAS_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_IMES_FULL[];
extern const char DESKTOP_TEXT_GNSS_SYSTEM_UNKNOWN_FULL[];
extern const char DESKTOP_TEXT_GNSS_COMPASS_NORTH[];
extern const char DESKTOP_TEXT_GNSS_COMPASS_EAST[];
extern const char DESKTOP_TEXT_GNSS_COMPASS_SOUTH[];
extern const char DESKTOP_TEXT_GNSS_COMPASS_WEST[];
extern const char DESKTOP_TEXT_GNSS_TRACKED[];
extern const char DESKTOP_TEXT_GNSS_VISIBLE[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_ENABLED[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_UPDATE_INTERVAL[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_MIN_ACTIVE[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_NAV_MODE[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_FIX_RATE[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_SYSTEM[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_GPS[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_GLONASS[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_GALILEO[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_BEIDOU[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_QZSS[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_IRNSS[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_SBAS[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_IMES[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_TIME_SYNC[];
extern const char DESKTOP_TEXT_GNSS_SETTINGS_ELECTRONIC_COMPASS[];
#define DESKTOP_TEXT_GNSS_NAV_MODE_COUNT 4U
extern const char *const DESKTOP_TEXT_GNSS_NAV_MODE_VALUES[DESKTOP_TEXT_GNSS_NAV_MODE_COUNT];
#define DESKTOP_TEXT_GNSS_FIX_RATE_COUNT 5U
extern const char *const DESKTOP_TEXT_GNSS_FIX_RATE_VALUES[DESKTOP_TEXT_GNSS_FIX_RATE_COUNT];
#define DESKTOP_TEXT_GNSS_SYSTEM_MODE_COUNT 2U
extern const char *const DESKTOP_TEXT_GNSS_SYSTEM_MODE_VALUES[DESKTOP_TEXT_GNSS_SYSTEM_MODE_COUNT];
extern const char DESKTOP_TEXT_GNSS_HEADER_UPDATE_INTERVAL_MS[];
extern const char DESKTOP_TEXT_GNSS_HEADER_MIN_ACTIVE_MS[];

extern const char DESKTOP_TEXT_LAUNCHER_START_FAILED_FORMAT[];
extern const char DESKTOP_TEXT_LAUNCHER_CLEANUP_FAILED_FORMAT[];
extern const char DESKTOP_TEXT_LAUNCHER_ACTION_DELETE[];
extern const char DESKTOP_TEXT_LAUNCHER_ACTION_PROPERTIES[];
extern const char DESKTOP_TEXT_LAUNCHER_DELETE_TITLE[];
extern const char DESKTOP_TEXT_LAUNCHER_DELETED[];
extern const char DESKTOP_TEXT_LAUNCHER_DELETE_FAILED_FORMAT[];
extern const char DESKTOP_TEXT_LAUNCHER_PROPERTIES_FAILED_FORMAT[];

/* MeshCore app text */
extern const char DESKTOP_TEXT_GNSS_ACQUISITION_NOW[];
extern const char DESKTOP_TEXT_GNSS_ACQUISITION_PROCESSING[];
extern const char DESKTOP_TEXT_GNSS_FAILED[];
extern const char DESKTOP_TEXT_GNSS_SATELLITES_RELOAD[];
extern const char DESKTOP_TEXT_GNSS_NO_SATELLITES[];
extern const char DESKTOP_TEXT_GNSS_RELOAD_FAILED[];

extern const char DESKTOP_TEXT_MESHCORE_ADVERT[];
extern const char DESKTOP_TEXT_MESHCORE_ADVERT_SELECT_TEXT[];
extern const char DESKTOP_TEXT_MESHCORE_ADVERT_BUTTON_FLOOD[];
extern const char DESKTOP_TEXT_MESHCORE_ADVERT_BUTTON_ZEROHOP[];
extern const char DESKTOP_TEXT_MESHCORE_LOCAL_ADVERT_QUEUED[];
extern const char DESKTOP_TEXT_MESHCORE_FLOOD_ADVERT_QUEUED[];
extern const char DESKTOP_TEXT_MESHCORE_MENU_RADIO_PRESET[];
extern const char DESKTOP_TEXT_MESHCORE_MENU_CHANNELS[];
extern const char DESKTOP_TEXT_MESHCORE_CHANNELS_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_CHANNELS_EMPTY[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_NAME[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ROLE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_PUBLIC_KEY[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_MULTI_ACKS[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADVERT_POSITION[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_PATH_HASH_SIZE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_CLIENT_REPEAT[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_OVERWRITE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_CHAT[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_REPEATER[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_ROOM[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_SENSOR[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_HOPS_LIMIT[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_CONTACT_ADD_POLICY[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_CONTACT_ADD_POLICY_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_FORWARDING[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_FORWARDING_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_BASE[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_LOCAT[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_ENVIRONMENT[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_TX_DELAY_FACTOR[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_DIRECT_TX_DELAY_FACTOR[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_DISABLE_FWD[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_LOOP_DETECT[];
#define DESKTOP_TEXT_MESHCORE_LOOP_DETECT_COUNT 4U
extern const char *const DESKTOP_TEXT_MESHCORE_LOOP_DETECT_VALUES[DESKTOP_TEXT_MESHCORE_LOOP_DETECT_COUNT];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_FLOOD_MAX[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADVERT_INTERVAL[];
extern const char DESKTOP_TEXT_MESHCORE_SETTINGS_FLOOD_ADVERT_INTERVAL[];
extern const char DESKTOP_TEXT_MESHCORE_RADIO_PRESET_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_CUSTOM[];
#define DESKTOP_TEXT_MESHCORE_RADIO_PRESET_COUNT 14U
extern const char *const DESKTOP_TEXT_MESHCORE_RADIO_PRESET_NAME_VALUES
	[DESKTOP_TEXT_MESHCORE_RADIO_PRESET_COUNT];
extern const char *const DESKTOP_TEXT_MESHCORE_RADIO_PRESET_SHORT_VALUES
	[DESKTOP_TEXT_MESHCORE_RADIO_PRESET_COUNT];
extern const char DESKTOP_TEXT_MESHCORE_RADIO_PRESET_CONFIRM_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_RADIO_PRESET_DETAIL_FORMAT[];
extern const char DESKTOP_TEXT_MESHCORE_ACTION_RESET[];
#define DESKTOP_TEXT_MESHCORE_ROLE_COUNT 4U
extern const char *const DESKTOP_TEXT_MESHCORE_ROLE_VALUES[DESKTOP_TEXT_MESHCORE_ROLE_COUNT];
extern const char DESKTOP_TEXT_MESHCORE_CHANNEL_SETTINGS_SECRET[];
extern const char DESKTOP_TEXT_MESHCORE_CHANNEL_SETTINGS_NAME[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_MULTI_ACKS[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_FLOOD_MAX[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_CONTACT_ADD_HOPS_LIMIT[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_TX_DELAY_FACTOR[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_DIRECT_TX_DELAY_FACTOR[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_ADVERT_INTERVAL[];
extern const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_FLOOD_ADVERT_INTERVAL[];
extern const char DESKTOP_TEXT_MESHCORE_PUBLIC_KEY_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_CHANNEL_SECRET_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_CHANNEL_QRCODE_BUTTON[];
extern const char DESKTOP_TEXT_MESHCORE_RESET_CONFIRM_TITLE[];
extern const char DESKTOP_TEXT_MESHCORE_RESET_CONFIRM_TEXT[];
extern const char DESKTOP_TEXT_MESHCORE_RESET_DONE[];
extern const char DESKTOP_TEXT_MESHCORE_TELEMETRY_MODE_DENY[];
extern const char DESKTOP_TEXT_MESHCORE_TELEMETRY_MODE_ALL[];

/* Messages app text */
extern const char DESKTOP_TEXT_MESSAGES_SENT[];
extern const char DESKTOP_TEXT_MESSAGES_SENT_MESSAGE[];
extern const char DESKTOP_TEXT_MESSAGES_SEND_FAILED[];
extern const char DESKTOP_TEXT_MESSAGES_SEND_FAILED_MESSAGE[];
extern const char DESKTOP_TEXT_MESSAGES_INBOX[];
extern const char DESKTOP_TEXT_MESSAGES_NEW_MESSAGE[];
extern const char DESKTOP_TEXT_MESSAGES_SELECT_TARGET[];
extern const char DESKTOP_TEXT_MESSAGES_LOADING[];
extern const char DESKTOP_TEXT_MESSAGES_NO_MORE_MESSAGES[];
extern const char DESKTOP_TEXT_MESSAGES_NO_TARGET[];
extern const char DESKTOP_TEXT_MESSAGES_INBOX_ROW_FORMAT[];
extern const char DESKTOP_TEXT_MESSAGES_LABEL_TO[];
extern const char DESKTOP_TEXT_MESSAGES_LABEL_ROUTE[];
extern const char DESKTOP_TEXT_MESSAGES_LABEL_CONTENT[];
extern const char DESKTOP_TEXT_MESSAGES_LABEL_EDIT_CONTENT[];
extern const char DESKTOP_TEXT_MESSAGES_ACTION_SEND[];
extern const char DESKTOP_TEXT_MESSAGES_CUSTOM[];
extern const char DESKTOP_TEXT_MESSAGES_DETAIL_NO_MESSAGE[];
extern const char DESKTOP_TEXT_MESSAGES_CHANNEL_SHORT[];
extern const char DESKTOP_TEXT_MESSAGES_PERSON_SHORT[];
extern const char DESKTOP_TEXT_MESSAGES_FLOOD_SHORT[];
#define DESKTOP_TEXT_MESSAGES_ROUTE_COUNT 2U
extern const char *const DESKTOP_TEXT_MESSAGES_ROUTE_VALUES[DESKTOP_TEXT_MESSAGES_ROUTE_COUNT];
extern const char DESKTOP_TEXT_MESSAGES_TIME_AGO_NOW[];
extern const char DESKTOP_TEXT_MESSAGES_TIME_AGO_MIN_FORMAT[];
extern const char DESKTOP_TEXT_MESSAGES_TIME_AGO_HOUR_FORMAT[];
extern const char DESKTOP_TEXT_MESSAGES_TIME_AGO_DAY_FORMAT[];
extern const char DESKTOP_TEXT_MESSAGES_TARGET_CHANNEL_FORMAT[];
extern const char DESKTOP_TEXT_MESSAGES_TARGET_CONTACT_FORMAT[];
#define DESKTOP_TEXT_MESSAGES_CANNED_COUNT 5U
extern const char *const DESKTOP_TEXT_MESSAGES_CANNED_VALUES[DESKTOP_TEXT_MESSAGES_CANNED_COUNT];
#define DESKTOP_TEXT_MESSAGES_CONTENT_OPTION_COUNT (DESKTOP_TEXT_MESSAGES_CANNED_COUNT + 1U)
extern const char *const DESKTOP_TEXT_MESSAGES_CONTENT_VALUES[DESKTOP_TEXT_MESSAGES_CONTENT_OPTION_COUNT];

/* Nodes app text */
extern const char DESKTOP_TEXT_NODES_SENT[];
extern const char DESKTOP_TEXT_NODES_REQUEST_SENT[];
extern const char DESKTOP_TEXT_NODES_REQUESTING[];
extern const char DESKTOP_TEXT_NODES_REQUEST_ERROR_BUSY_RETRY_LATER[];
extern const char DESKTOP_TEXT_NODES_REQUEST_ERROR_FAILURE[];
extern const char DESKTOP_TEXT_NODES_REQUEST_ERROR_NEIGHBOR_NOT_ALLOW[];
extern const char DESKTOP_TEXT_NODES_DELETED[];
extern const char DESKTOP_TEXT_NODES_NODE_DELETED[];
extern const char DESKTOP_TEXT_NODES_DISCOVER_PATH_REQUEST_SENT[];
extern const char DESKTOP_TEXT_NODES_TRACE_PATH_REQUEST_SENT[];
extern const char DESKTOP_TEXT_NODES_BROADCAST_REQUEST_SENT[];
extern const char DESKTOP_TEXT_NODES_NODE[];
extern const char DESKTOP_TEXT_NODES_NO_NODE[];
extern const char DESKTOP_TEXT_NODES_NO_NODES[];
extern const char DESKTOP_TEXT_NODES_MENU_ALIAS[];
extern const char DESKTOP_TEXT_NODES_MENU_NAME[];
extern const char DESKTOP_TEXT_NODES_MENU_ROLE[];
extern const char DESKTOP_TEXT_NODES_MENU_PUBLIC_KEY[];
extern const char DESKTOP_TEXT_NODES_MENU_PERMISSION[];
extern const char DESKTOP_TEXT_NODES_MENU_BROADCAST[];
extern const char DESKTOP_TEXT_NODES_MENU_BATTERY[];
extern const char DESKTOP_TEXT_NODES_MENU_LATITUDE[];
extern const char DESKTOP_TEXT_NODES_MENU_LONGITUDE[];
extern const char DESKTOP_TEXT_NODES_MENU_TELEMETRY[];
extern const char DESKTOP_TEXT_NODES_MENU_DISCOVER_PATH[];
extern const char DESKTOP_TEXT_NODES_MENU_TRACE_PATH[];
extern const char DESKTOP_TEXT_NODES_MENU_DELETE[];
extern const char DESKTOP_TEXT_NODES_PERMISSION_TITLE[];
extern const char DESKTOP_TEXT_NODES_PERMISSION_BASE[];
extern const char DESKTOP_TEXT_NODES_PERMISSION_LOCATION[];
extern const char DESKTOP_TEXT_NODES_PERMISSION_ENVIRONMENT[];
extern const char DESKTOP_TEXT_NODES_ROLE_REPEATER[];
extern const char DESKTOP_TEXT_NODES_ROLE_CLIENT[];
extern const char DESKTOP_TEXT_NODES_TITLE_DISCOVER_PATH[];
extern const char DESKTOP_TEXT_NODES_TITLE_TRACE_PATH[];
extern const char DESKTOP_TEXT_NODES_BUTTON_REDISCOVER[];
extern const char DESKTOP_TEXT_NODES_BUTTON_RETRACE[];
extern const char DESKTOP_TEXT_NODES_DISCOVERING[];
extern const char DESKTOP_TEXT_NODES_TRACING[];
extern const char DESKTOP_TEXT_NODES_STATUS_TRACE_SUCCESS[];
extern const char DESKTOP_TEXT_NODES_STATUS_TRACE_WAITING[];
extern const char DESKTOP_TEXT_NODES_STATUS_TRACE_NONE[];
extern const char DESKTOP_TEXT_NODES_ACTION_CONFIRM_DELETE_HEADER[];
extern const char DESKTOP_TEXT_NODES_ACTION_CONFIRM_DELETE_TEXT_FORMAT[];
extern const char DESKTOP_TEXT_NODES_DISCOVER_READY_TEXT_FORMAT[];
extern const char DESKTOP_TEXT_NODES_TRACE_PATH_TEXT_FORMAT[];
extern const char DESKTOP_TEXT_NODES_TELEMETRY_TITLE[];
extern const char DESKTOP_TEXT_NODES_TELEMETRY_NO_NODE[];
extern const char DESKTOP_TEXT_NODES_PUBLIC_KEY_TITLE[];
extern const char DESKTOP_TEXT_NODES_TIME_AGO_NOW[];
extern const char DESKTOP_TEXT_NODES_TIME_AGO_OVER_7D[];
extern const char DESKTOP_TEXT_NODES_TIME_AGO_MIN_FORMAT[];
extern const char DESKTOP_TEXT_NODES_TIME_AGO_HOUR_FORMAT[];
extern const char DESKTOP_TEXT_NODES_TIME_AGO_DAY_FORMAT[];
extern const char DESKTOP_TEXT_NODES_DASH[];
extern const char DESKTOP_TEXT_NODES_NEIGHBOR[];

/* Telemetry app text */
extern const char DESKTOP_TEXT_TELEMETRY_READINGS[];
extern const char DESKTOP_TEXT_TELEMETRY_TRIGGER_SAMPLE[];
extern const char DESKTOP_TEXT_TELEMETRY_SETTINGS_ENABLED[];
extern const char DESKTOP_TEXT_TELEMETRY_SETTINGS_INTERVAL[];
extern const char DESKTOP_TEXT_TELEMETRY_HEADER_INTERVAL_MS[];
extern const char DESKTOP_TEXT_TELEMETRY_NO_READINGS[];
extern const char DESKTOP_TEXT_TELEMETRY_NO_DATA[];
extern const char DESKTOP_TEXT_TELEMETRY_SAMPLE_TRIGGERED[];
extern const char DESKTOP_TEXT_TELEMETRY_SAMPLE_DISABLED[];
extern const char DESKTOP_TEXT_TELEMETRY_SAMPLE_FAILED[];
extern const char DESKTOP_TEXT_TELEMETRY_OPEN_FAILED[];
extern const char DESKTOP_TEXT_TELEMETRY_READING_DETAIL_FORMAT[];

/* Power app text */
extern const char DESKTOP_TEXT_POWER_SETTINGS_LOW_VOLTAGE_TIMEOUT[];
extern const char DESKTOP_TEXT_POWER_SETTINGS_LOSING_POWER_TIMEOUT[];
extern const char DESKTOP_TEXT_POWER_SETTINGS_NO_CONNECTION_TIMEOUT[];
extern const char DESKTOP_TEXT_POWER_VALUE_SECONDS_FORMAT[];
extern const char DESKTOP_TEXT_POWER_VALUE_TEMPERATURE_FORMAT[];

/* System app text */
extern const char DESKTOP_TEXT_SYSTEM_MENU_INFORMATION[];
extern const char DESKTOP_TEXT_SYSTEM_MENU_IDENTITY[];
extern const char DESKTOP_TEXT_SYSTEM_MENU_HARDWARE[];
extern const char DESKTOP_TEXT_SYSTEM_MENU_FIRMWARE[];
extern const char DESKTOP_TEXT_SYSTEM_MENU_RUNTIME[];
extern const char DESKTOP_TEXT_SYSTEM_MENU_DEVICES[];
extern const char DESKTOP_TEXT_SYSTEM_MENU_INDICATOR[];
extern const char DESKTOP_TEXT_INDICATOR_TITLE[];
extern const char DESKTOP_TEXT_INDICATOR_LIGHT[];
extern const char DESKTOP_TEXT_INDICATOR_HEARTBEAT[];
extern const char DESKTOP_TEXT_INDICATOR_LIGHT_MESSAGES[];
extern const char DESKTOP_TEXT_INDICATOR_LIGHT_SYSTEM[];
extern const char DESKTOP_TEXT_INDICATOR_BUZZER[];
extern const char DESKTOP_TEXT_INDICATOR_INPUT[];
extern const char DESKTOP_TEXT_INDICATOR_DM[];
extern const char DESKTOP_TEXT_INDICATOR_CHANNEL[];
extern const char DESKTOP_TEXT_INDICATOR_SYSTEM[];
extern const char DESKTOP_TEXT_SYSTEM_INFO_IDENTITY_FORMAT[];
extern const char DESKTOP_TEXT_SYSTEM_INFO_HARDWARE_FORMAT[];
extern const char DESKTOP_TEXT_SYSTEM_INFO_HARDWARE_BLUETOOTH_FORMAT[];
extern const char DESKTOP_TEXT_SYSTEM_INFO_FIRMWARE_FORMAT[];
extern const char DESKTOP_TEXT_SYSTEM_INFO_RUNTIME_FORMAT[];
extern const char DESKTOP_TEXT_SYSTEM_DEVICE_STATE_READY[];
extern const char DESKTOP_TEXT_SYSTEM_DEVICE_STATE_DISABLED[];
extern const char DESKTOP_TEXT_SYSTEM_DEVICE_USAGE_FORMAT[];
extern const char DESKTOP_TEXT_SYSTEM_DEVICE_FORMAT[];

/* Radio app text */
extern const char DESKTOP_TEXT_RADIO_TITLE[];
extern const char DESKTOP_TEXT_RADIO_PACKET[];
extern const char DESKTOP_TEXT_RADIO_CONTINUOUS_WAVE[];
extern const char DESKTOP_TEXT_RADIO_NOISE_ANALYZER[];
extern const char DESKTOP_TEXT_RADIO_CALIBRATE_NF[];
extern const char DESKTOP_TEXT_RADIO_AGC_RESET[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS[];
extern const char DESKTOP_TEXT_RADIO_DISABLED[];
extern const char DESKTOP_TEXT_RADIO_CALIBRATING[];
extern const char DESKTOP_TEXT_RADIO_RX_ONLY_MODE[];

extern const char DESKTOP_TEXT_RADIO_SEND_AS_TEXT[];
extern const char DESKTOP_TEXT_RADIO_SEND_AS_HEX[];
extern const char DESKTOP_TEXT_RADIO_PACKET_CAPTURE[];

extern const char DESKTOP_TEXT_RADIO_CAPTURE[];
extern const char DESKTOP_TEXT_RADIO_RSSI[];
extern const char DESKTOP_TEXT_RADIO_SNR[];
extern const char DESKTOP_TEXT_RADIO_LEN[];
extern const char DESKTOP_TEXT_RADIO_HEX[];
extern const char DESKTOP_TEXT_RADIO_TEXT[];
extern const char DESKTOP_TEXT_RADIO_EMPTY[];
extern const char DESKTOP_TEXT_RADIO_DASH[];

extern const char DESKTOP_TEXT_RADIO_NOISE[];
extern const char DESKTOP_TEXT_RADIO_DBM[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_MIN_MAX[];
extern const char DESKTOP_TEXT_RADIO_MIN_MAX_DASH[];
extern const char DESKTOP_TEXT_RADIO_RX_UNKNOWN[];
extern const char DESKTOP_TEXT_RADIO_NA[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_NF_STATUS[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_NF_DASH_STATUS[];
extern const char DESKTOP_TEXT_RADIO_ACT[];
extern const char DESKTOP_TEXT_RADIO_QUIET[];

extern const char DESKTOP_TEXT_RADIO_SETTINGS_ENABLED[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_RX_ONLY[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_FREQUENCY[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_BANDWIDTH[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_DATA_RATE[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_CODING_RATE[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_PREAMBLE[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_TX_POWER[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_PACKET_CRC[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_RX_BOOSTED[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_DUTY_CYCLE[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_DUTY_RX_TIME[];
extern const char DESKTOP_TEXT_RADIO_SETTINGS_DUTY_SLEEP_TIME[];

extern const char DESKTOP_TEXT_RADIO_CW_TX_POWER[];
extern const char DESKTOP_TEXT_RADIO_CW_DURATION[];
extern const char DESKTOP_TEXT_RADIO_CW_EXECUTE[];

extern const char DESKTOP_TEXT_RADIO_HEADER_FREQUENCY_HZ[];
extern const char DESKTOP_TEXT_RADIO_HEADER_PREAMBLE[];
extern const char DESKTOP_TEXT_RADIO_HEADER_DUTY_RX_MS[];
extern const char DESKTOP_TEXT_RADIO_HEADER_DUTY_SLEEP_MS[];

extern const char DESKTOP_TEXT_RADIO_REJECTED[];
extern const char DESKTOP_TEXT_RADIO_EXECUTING[];
extern const char DESKTOP_TEXT_RADIO_FINISHED[];

extern const char DESKTOP_TEXT_RADIO_FORMAT_ERROR_CODE[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_LEN_TOA[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_TEXT_MESSAGE_HEADER[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_HEX_PAYLOAD_HEADER[];
extern const char DESKTOP_TEXT_RADIO_FORMAT_U_MS[];

#define DESKTOP_TEXT_RADIO_BW_COUNT 10U
extern const char *const DESKTOP_TEXT_RADIO_BW_VALUES[DESKTOP_TEXT_RADIO_BW_COUNT];

/* Desktop views text */
extern const char DESKTOP_TEXT_VIEW_MENU_INVALID_APP[];
extern const char DESKTOP_TEXT_VIEW_POWER_SLEEP[];
extern const char DESKTOP_TEXT_VIEW_POWER_SHUTDOWN[];
extern const char DESKTOP_TEXT_VIEW_POWER_REBOOT[];
extern const char DESKTOP_TEXT_VIEW_POWER_INVALID[];
extern const char DESKTOP_TEXT_VIEW_POWER_SLEEP_SELECTED[];
extern const char DESKTOP_TEXT_VIEW_POWER_SHUTDOWN_SELECTED[];
extern const char DESKTOP_TEXT_VIEW_POWER_REBOOT_SELECTED[];

/* Dashboard widgets text */
#define DESKTOP_TEXT_WIDGET_CLOCK_DAY_COUNT 7U
extern const char *const DESKTOP_TEXT_WIDGET_CLOCK_DAY_VALUES[DESKTOP_TEXT_WIDGET_CLOCK_DAY_COUNT];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_MERIDIEM_AM[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_MERIDIEM_PM[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_HMS[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_TIME[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_DAY[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_DATE[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_SYNC[];
extern const char DESKTOP_TEXT_WIDGET_CLOCK_UNSYNC[];

#define DESKTOP_TEXT_WIDGET_COMPASS_DIRECTION_COUNT 8U
extern const char *const DESKTOP_TEXT_WIDGET_COMPASS_DIRECTION_VALUES[DESKTOP_TEXT_WIDGET_COMPASS_DIRECTION_COUNT];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_PLACEHOLDER_HEADING[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_PLACEHOLDER_DIRECTION[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_LABEL[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_UNAVAILABLE[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_UNRELIABLE[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_LOW[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_MEDIUM[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_HIGH[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_OFF[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_WAIT[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_CALIBRATE[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_LEVEL[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_OK[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_ERROR[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_CALIBRATION_TITLE[];
extern const char DESKTOP_TEXT_WIDGET_COMPASS_CALIBRATION_ACTION[];

extern const char DESKTOP_TEXT_WIDGET_INFO_ICON_INFO[];
extern const char DESKTOP_TEXT_WIDGET_INFO_LABEL_VERSION[];
extern const char DESKTOP_TEXT_WIDGET_INFO_LABEL_SN[];
extern const char DESKTOP_TEXT_WIDGET_INFO_PLACEHOLDER_DEVICE[];
extern const char DESKTOP_TEXT_WIDGET_INFO_PLACEHOLDER_VERSION[];
extern const char DESKTOP_TEXT_WIDGET_INFO_SERIAL_UNKNOWN[];

extern const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE[];
extern const char DESKTOP_TEXT_WIDGET_MESHCORE_SYNC_WORD_PRIVATE[];
extern const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_CLIENT[];
extern const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_REPEATER[];
extern const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_ROOM[];
extern const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_SENSOR[];

extern const char DESKTOP_TEXT_WIDGET_MESSAGES_NO_MORE_MESSAGES[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_EMPTY[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_DIRECT[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_CHANNEL[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_FLOOD[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_SELECTED_LINE_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_UNREAD[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_NEWER[];
extern const char DESKTOP_TEXT_WIDGET_MESSAGES_POSITION_FORMAT[];

extern const char DESKTOP_TEXT_WIDGET_NODES_ROOM[];
extern const char DESKTOP_TEXT_WIDGET_NODES_SENSOR[];
extern const char DESKTOP_TEXT_WIDGET_NODES_ROLE_UNKNOWN[];
extern const char DESKTOP_TEXT_WIDGET_NODES_ADVERT[];
extern const char DESKTOP_TEXT_WIDGET_NODES_ADVERT_REQUEST_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_NODES_CAPACITY_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_NODES_UNKNOWN_NAME[];
extern const char DESKTOP_TEXT_WIDGET_NODES_EMPTY[];
extern const char DESKTOP_TEXT_WIDGET_NODES_CLI[];
extern const char DESKTOP_TEXT_WIDGET_NODES_RPT[];
extern const char DESKTOP_TEXT_WIDGET_NODES_BROADCAST[];
extern const char DESKTOP_TEXT_WIDGET_NODES_CONTACT_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_NODES_ROLE_COUNTS_FORMAT[];

extern const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_DIR[];
extern const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_DEG[];
extern const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_MIN[];
extern const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_ALT[];
extern const char DESKTOP_TEXT_WIDGET_POSITION_LABEL_POSITION[];
extern const char DESKTOP_TEXT_WIDGET_POSITION_LABEL_ALTITUDE[];
extern const char DESKTOP_TEXT_WIDGET_POSITION_UNIT_METER[];

extern const char DESKTOP_TEXT_WIDGET_POWER_PLACEHOLDER_SOC[];
extern const char DESKTOP_TEXT_WIDGET_POWER_PLACEHOLDER_VOLTAGE[];
extern const char DESKTOP_TEXT_WIDGET_POWER_TEMP_NC[];
extern const char DESKTOP_TEXT_WIDGET_POWER_VOLTAGE_FORMAT[];

#define DESKTOP_TEXT_WIDGET_RADIO_BW_SHORT_COUNT 15U
extern const char *const DESKTOP_TEXT_WIDGET_RADIO_BW_SHORT_VALUES[DESKTOP_TEXT_WIDGET_RADIO_BW_SHORT_COUNT];
extern const char DESKTOP_TEXT_WIDGET_RADIO_PLACEHOLDER_FREQUENCY[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_PLACEHOLDER_VALUE[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_LR[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_OFF[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_TX[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_RX[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_IDLE[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_BW_KHZ_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_TX_POWER_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_SF_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_RADIO_CR_FORMAT[];

extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_PAGE_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_VALUE_MISSING[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_VALUE_OVERFLOW[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_DIE_TEMP[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_TEMP[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_PRESS[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_HUMIDITY[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_VOLTAGE[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_CURRENT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_SHORT_BATTERY[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_C[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_KPA[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_PERCENT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_LUX[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_V[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_A[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_ACCEL[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_GYRO[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_UNIT_GAUSS[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_STATUS_ON[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_STATUS_OFF[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_NO_DATA[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_BINDINGS_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_INTERVAL_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_AGE_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_COUNT_FORMAT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_ACCEL[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_GYRO[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_MAGN[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_DIE_TEMP[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_AMBIENT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_PRESS[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_HUMIDITY[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_LIGHT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_VOLTAGE[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_CURRENT[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_BATTERY[];
extern const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_CHANNEL[];
#define DESKTOP_TEXT_WIDGET_TELEMETRY_AXIS_COUNT 4U
extern const char *const
	DESKTOP_TEXT_WIDGET_TELEMETRY_AXIS_VALUES[DESKTOP_TEXT_WIDGET_TELEMETRY_AXIS_COUNT];

extern const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_OFF[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_SLEEP[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_ACQ[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_TRACK[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_ERROR[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_LABEL_HDOP[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_LABEL_SATS[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_TZ_LUT[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_PLACEHOLDER_HDOP[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_PLACEHOLDER_SATS[];
extern const char DESKTOP_TEXT_WIDGET_SATELLITE_PLACEHOLDER_UTC[];

extern const char DESKTOP_TEXT_WIDGET_USAGE_TITLE_RAM_USAGE[];
extern const char DESKTOP_TEXT_WIDGET_USAGE_LABEL_SYSTEM[];
extern const char DESKTOP_TEXT_WIDGET_USAGE_LABEL_GRAPH[];
extern const char DESKTOP_TEXT_WIDGET_USAGE_NOT_AVAILABLE[];
extern const char DESKTOP_TEXT_WIDGET_USAGE_VALUE_FORMAT[];

#ifdef __cplusplus
}
#endif
