/* SPDX-License-Identifier: Apache-2.0 */

/* Copyright (c) 2026 FoBE Studio */

/**
 * @file
 * @brief Meshbus MBA metadata layout and section registration
 */

#ifndef MBS_LLEXT_METADATA_H_
#define MBS_LLEXT_METADATA_H_

#include <stddef.h>
#include <stdint.h>

#include <zephyr/toolchain.h>
#include <zephyr/sys/util.h>

#include <mbs_llext_metadata_version.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Maximum LLEXT ID length (without trailing NUL). */
#define MBS_LLEXT_ID_MAX_LEN 31
/** Maximum LLEXT version string length (without trailing NUL). */
#define MBS_LLEXT_VERSION_MAX_LEN 15
/** Maximum app display name length (without trailing NUL). */
#define MBS_LLEXT_NAME_MAX_LEN 63
/** Maximum app symbol name length (without trailing NUL). */
#define MBS_LLEXT_SYMBOL_MAX_LEN 63
/** Maximum target string length (without trailing NUL). */
#define MBS_LLEXT_TARGET_MAX_LEN 63
/** Section name for LLEXT metadata blobs in `.mba` ELF files. */
#define MBS_LLEXT_METADATA_SECTION ".meshbus.llext.meta"
/** Section name for app metadata blob in `.mba` ELF files. */
#define MBS_LLEXT_APP_METADATA_SECTION MBS_LLEXT_METADATA_SECTION
/** Magic value for @ref mbs_llext_app_metadata. */
#define MBS_LLEXT_APP_METADATA_MAGIC 0x4D424C41U
/** Supported app metadata structure version. */
#define MBS_LLEXT_APP_METADATA_VERSION MBS_LLEXT_METADATA_VERSION
/** Size of @ref mbs_llext_app_metadata on the wire. */
#define MBS_LLEXT_APP_METADATA_SIZE 368U
/** Fixed app icon width in pixels. */
#define MBS_LLEXT_APP_ICON_WIDTH 10U
/** Fixed app icon height in pixels. */
#define MBS_LLEXT_APP_ICON_HEIGHT 10U
/** Exact fixed 10x10 raw mono app icon payload size, in bytes. */
#define MBS_LLEXT_APP_ICON_DATA_SIZE \
	(((MBS_LLEXT_APP_ICON_WIDTH + 7U) / 8U) * MBS_LLEXT_APP_ICON_HEIGHT)
/** Maximum fixed 10x10 raw mono app icon payload length, in bytes. */
#define MBS_LLEXT_APP_ICON_DATA_MAX_LEN MBS_LLEXT_APP_ICON_DATA_SIZE

/**
 * @brief Desktop app metadata descriptor stored in
 *        @ref MBS_LLEXT_APP_METADATA_SECTION.
 *
 * `edk_version`, `target`, `heap_size`, and `icon_data` are generated by build
 * tooling. App authors must not hand-write those fields in source YAML. Icons
 * are always fixed 10x10 raw mono bitmap payloads, with
 * one byte per 8-pixel row chunk. Empty `icon_data_size` means the Desktop
 * launcher should use its default LLEXT app icon.
 */
struct mbs_llext_app_metadata {
	uint32_t magic;
	uint32_t metadata_version;
	uint32_t size;
	uint32_t stack_size;
	uint32_t heap_size;
	uint32_t icon_data_size;
	char id[MBS_LLEXT_ID_MAX_LEN + 1];
	char name[MBS_LLEXT_NAME_MAX_LEN + 1];
	char app_version[MBS_LLEXT_VERSION_MAX_LEN + 1];
	char entry_point_symbol[MBS_LLEXT_SYMBOL_MAX_LEN + 1];
	char edk_version[MBS_LLEXT_VERSION_MAX_LEN + 1];
	uint8_t compatibility_reserved[48];
	char target[MBS_LLEXT_TARGET_MAX_LEN + 1];
	uint8_t icon_data[MBS_LLEXT_APP_ICON_DATA_MAX_LEN];
	uint8_t reserved[20];
};

BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, id) == 24U,
	     "meshbus LLEXT app metadata id offset changed");
BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, entry_point_symbol) == 136U,
	     "meshbus LLEXT app metadata entry offset changed");
BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, edk_version) == 200U,
	     "meshbus LLEXT app metadata EDK version offset changed");
BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, compatibility_reserved) == 216U,
	     "meshbus LLEXT app metadata compatibility reserved offset changed");
BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, target) == 264U,
	     "meshbus LLEXT app metadata target offset changed");
BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, icon_data) == 328U,
	     "meshbus LLEXT app metadata icon offset changed");
BUILD_ASSERT(offsetof(struct mbs_llext_app_metadata, reserved) == 348U,
	     "meshbus LLEXT app metadata reserved offset changed");
BUILD_ASSERT(sizeof(struct mbs_llext_app_metadata) ==
	     MBS_LLEXT_APP_METADATA_SIZE,
	     "meshbus LLEXT app metadata layout changed");

/** @brief Attribute for placing app metadata into the LLEXT metadata section. */
#define MBS_LLEXT_APP_METADATA_ATTR \
	Z_GENERIC_SECTION(MBS_LLEXT_APP_METADATA_SECTION) __used


#ifdef __cplusplus
}
#endif

#endif /* MBS_LLEXT_METADATA_H_ */
