#pragma once

/** Widgets ID */
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_RADIO     0
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_MESHCORE  1
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_MESSAGES  2
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_NODES     3
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_SATELLITE 4
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_POSITION  5
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_COMPASS   6
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_CLOCK     7
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_POWER     8
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_TELEMETRY 9
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_USAGE     10
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_ID_INFO      11

/** Widgets title */
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_USAGE     "Usage"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_SATELLITE "Satellite"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_RADIO     "Radio"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_POWER     "Power"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_POSITION  "Position"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_NODES     "Nodes"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_COMPASS   "Compass"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_MESSAGES  "Messages"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_MESHCORE  "MeshCore"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_INFO      "Info"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_CLOCK     "Clock"
#define MESHBUS_DESKTOP_DASHBOARD_WIDGET_TITLE_TELEMETRY "Telemetry"
