/* SPDX-License-Identifier: Apache-2.0 */

#include "text/desktop_text.h"

const char DESKTOP_TEXT_COMMON_OFF[] = "关";
const char DESKTOP_TEXT_COMMON_ON[] = "开";
const char DESKTOP_TEXT_COMMON_NO[] = "否";
const char DESKTOP_TEXT_COMMON_YES[] = "是";
const char *const DESKTOP_TEXT_COMMON_BOOL_VALUES[2] = {
	DESKTOP_TEXT_COMMON_OFF,
	DESKTOP_TEXT_COMMON_ON,
};
const char *const DESKTOP_TEXT_COMMON_NO_YES_VALUES[2] = {
	DESKTOP_TEXT_COMMON_NO,
	DESKTOP_TEXT_COMMON_YES,
};
const char DESKTOP_TEXT_COMMON_SETTINGS_APPLIED[] = "设置已应用";
const char DESKTOP_TEXT_COMMON_SETTINGS_RESET[] = "设置已重置";
const char DESKTOP_TEXT_COMMON_SETTINGS_INVALID[] = "设置无效";
const char DESKTOP_TEXT_COMMON_ACTION_APPLY[] = "> 应用";
const char DESKTOP_TEXT_COMMON_ACTION_RESET[] = "> 重置";
const char DESKTOP_TEXT_COMMON_BUTTON_CLEAR[] = "清除";
const char DESKTOP_TEXT_COMMON_BUTTON_START[] = "开始";
const char DESKTOP_TEXT_COMMON_BUTTON_STOP[] = "停止";
const char DESKTOP_TEXT_COMMON_NO_DATA[] = "(无数据)";
const char DESKTOP_TEXT_COMMON_NONE[] = "<无>";
const char DESKTOP_TEXT_COMMON_UNKNOWN[] = "--";
const char DESKTOP_TEXT_COMMON_OK[] = "OK";
const char DESKTOP_TEXT_COMMON_RESET[] = "重置";
const char DESKTOP_TEXT_COMMON_APPLY[] = "应用";
const char DESKTOP_TEXT_COMMON_CANCEL[] = "取消";
const char DESKTOP_TEXT_COMMON_REFRESH[] = "刷新";
const char DESKTOP_TEXT_COMMON_MENU_SETTINGS[] = "设置";
const char DESKTOP_TEXT_COMMON_MENU_STATS[] = "统计";
const char DESKTOP_TEXT_COMMON_BUTTON_REPLY[] = "回复";
const char DESKTOP_TEXT_COMMON_EMPTY[] = "";
const char DESKTOP_TEXT_COMMON_ROUTE[] = ">";
const char DESKTOP_TEXT_COMMON_NOT_AVAILABLE[] = "不适用";
const char DESKTOP_TEXT_COMMON_UNKNOWN_WORD[] = "未知";
const char DESKTOP_TEXT_COMMON_YES_LOWER[] = "是";
const char DESKTOP_TEXT_COMMON_NO_LOWER[] = "否";
const char DESKTOP_TEXT_COMMON_RESET_CONFIRM_TEXT[] = "重置为默认设置?";

const char DESKTOP_TEXT_BLUETOOTH_TITLE[] = "蓝牙";
const char DESKTOP_TEXT_CLOCK_TITLE[] = "时钟";
const char DESKTOP_TEXT_DISPLAY_TITLE[] = "显示";
const char DESKTOP_TEXT_GNSS_TITLE[] = "GNSS";
const char DESKTOP_TEXT_RADIO_TITLE[] = "无线电";
const char DESKTOP_TEXT_LAUNCHER_TITLE[] = "启动器";
const char DESKTOP_TEXT_MESHCORE_TITLE[] = "MeshCore";
const char DESKTOP_TEXT_MESSAGES_TITLE[] = "消息";
const char DESKTOP_TEXT_NODES_TITLE[] = "节点";
const char DESKTOP_TEXT_POWER_TITLE[] = "电源";
const char DESKTOP_TEXT_SYSTEM_TITLE[] = "系统";
const char DESKTOP_TEXT_TELEMETRY_TITLE[] = "遥测";

const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_ENABLED[] = "启用";
const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_MESHCORE_COMPANION[] = "MeshCore NUS";
const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_PASSKEY_MODE[] = "配对码模式";
const char DESKTOP_TEXT_BLUETOOTH_SETTINGS_FIXED_PASSKEY[] = "固定配对码";
const char *const DESKTOP_TEXT_BLUETOOTH_PASSKEY_MODE_VALUES[DESKTOP_TEXT_BLUETOOTH_PASSKEY_MODE_COUNT] = {
	"随机",
	"固定",
};

const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_PAIRING_HEADER[] = "设备配对";
const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_CONNECTED[] = "已连接";
const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_DISCONNECTED[] = "已断开";
const char DESKTOP_TEXT_NOTIFY_BLUETOOTH_PAIRING_CODE_FORMAT[] = "配对码: %06u";

const char DESKTOP_TEXT_CLOCK_SETTINGS_FORMAT[] = "格式";
const char DESKTOP_TEXT_CLOCK_SETTINGS_UTC_OFFSET[] = "UTC 偏移";
const char DESKTOP_TEXT_CLOCK_UTC_OFFSET_FORMAT[] = "%c%02d:%02d";
const char *const DESKTOP_TEXT_CLOCK_FORMAT_VALUES[DESKTOP_TEXT_CLOCK_FORMAT_COUNT] = {
	"12h",
	"24h",
};

const char DESKTOP_TEXT_DISPLAY_SETTINGS_BRIGHTNESS[] = "亮度";
const char DESKTOP_TEXT_DISPLAY_SETTINGS_SLEEP_TIMEOUT[] = "休眠延时";
const char DESKTOP_TEXT_DISPLAY_SETTINGS_INVERT[] = "反色";
const char DESKTOP_TEXT_DISPLAY_NEVER[] = "从不";

const char DESKTOP_TEXT_GNSS_STATUS[] = "状态";
const char DESKTOP_TEXT_GNSS_STATUS_TITLE[] = "GNSS 状态";
const char DESKTOP_TEXT_GNSS_SATELLITES[] = "卫星";
const char DESKTOP_TEXT_GNSS_ACQUISITION[] = "定位";
const char DESKTOP_TEXT_GNSS_ACTION_RELOAD[] = "> 重新加载";
const char DESKTOP_TEXT_GNSS_NO_SATELLITES_PAREN[] = "(无卫星)";
const char DESKTOP_TEXT_GNSS_STATUS_LOADING[] = "正在加载 GNSS 状态...";
const char DESKTOP_TEXT_GNSS_SATELLITE[] = "卫星";
const char DESKTOP_TEXT_GNSS_NO_SATELLITE_SELECTED[] = "未选择卫星.";
const char DESKTOP_TEXT_GNSS_SATELLITE_DETAIL_FORMAT[] =
	"SNR:       %u\n"
	"EL:        %u\n"
	"AZ:        %u\n"
	"已跟踪:   %s\n"
	"已校正:   %s";
const char DESKTOP_TEXT_GNSS_STATUS_DETAIL_FORMAT[] =
	"设备:\n"
	"  启用:      %s\n"
	"  状态:      %s\n"
	"  定位状态:  %s\n"
	"  质量:      %s\n"
	"  HDOP:       %s\n"
	"  已跟踪:    %s\n"
	"  可见:      %s\n"
	"位置:\n"
	"  纬度:      %s\n"
	"  经度:      %s\n"
	"  海拔:      %s\n"
	"  速度:      %s\n"
	"  方位:      %s\n"
	"UTC:\n"
	"  %s";
const char DESKTOP_TEXT_GNSS_NOT_AVAILABLE[] = "不适用";
const char DESKTOP_TEXT_GNSS_UNIT_DEG[] = "deg";
const char DESKTOP_TEXT_GNSS_UNIT_M[] = "m";
const char DESKTOP_TEXT_GNSS_UNIT_MPS[] = "m/s";
const char DESKTOP_TEXT_GNSS_STATE_SLEEP[] = "休眠";
const char DESKTOP_TEXT_GNSS_STATE_ACQUIRING[] = "定位中";
const char DESKTOP_TEXT_GNSS_STATE_TRACK[] = "跟踪";
const char DESKTOP_TEXT_GNSS_STATE_ERROR[] = "错误";
const char DESKTOP_TEXT_GNSS_FIX_NO_FIX[] = "未定位";
const char DESKTOP_TEXT_GNSS_FIX_GNSS_FIX[] = "GNSS 定位";
const char DESKTOP_TEXT_GNSS_FIX_DGNSS_FIX[] = "DGNSS 定位";
const char DESKTOP_TEXT_GNSS_FIX_ESTIMATED_FIX[] = "估算定位";
const char DESKTOP_TEXT_GNSS_QUALITY_INVALID[] = "无效";
const char DESKTOP_TEXT_GNSS_QUALITY_GNSS_SPS[] = "GNSS 单点";
const char DESKTOP_TEXT_GNSS_QUALITY_DGNSS[] = "差分";
const char DESKTOP_TEXT_GNSS_QUALITY_GNSS_PPS[] = "GNSS 精密";
const char DESKTOP_TEXT_GNSS_QUALITY_RTK[] = "rtk";
const char DESKTOP_TEXT_GNSS_QUALITY_FLOAT_RTK[] = "浮点 RTK";
const char DESKTOP_TEXT_GNSS_QUALITY_ESTIMATED[] = "估算";
const char DESKTOP_TEXT_GNSS_SYSTEM_GPS_SHORT[] = "GPS";
const char DESKTOP_TEXT_GNSS_SYSTEM_GLONASS_SHORT[] = "GLO";
const char DESKTOP_TEXT_GNSS_SYSTEM_GALILEO_SHORT[] = "GAL";
const char DESKTOP_TEXT_GNSS_SYSTEM_BEIDOU_SHORT[] = "BDS";
const char DESKTOP_TEXT_GNSS_SYSTEM_QZSS_SHORT[] = "QZS";
const char DESKTOP_TEXT_GNSS_SYSTEM_IRNSS_SHORT[] = "IRN";
const char DESKTOP_TEXT_GNSS_SYSTEM_SBAS_SHORT[] = "SBS";
const char DESKTOP_TEXT_GNSS_SYSTEM_IMES_SHORT[] = "IMS";
const char DESKTOP_TEXT_GNSS_SYSTEM_UNKNOWN_SHORT[] = "UNK";
const char DESKTOP_TEXT_GNSS_SYSTEM_GPS_FULL[] = "GPS";
const char DESKTOP_TEXT_GNSS_SYSTEM_GLONASS_FULL[] = "GLONASS";
const char DESKTOP_TEXT_GNSS_SYSTEM_GALILEO_FULL[] = "GALILEO";
const char DESKTOP_TEXT_GNSS_SYSTEM_BEIDOU_FULL[] = "BEIDOU";
const char DESKTOP_TEXT_GNSS_SYSTEM_QZSS_FULL[] = "QZSS";
const char DESKTOP_TEXT_GNSS_SYSTEM_IRNSS_FULL[] = "IRNSS";
const char DESKTOP_TEXT_GNSS_SYSTEM_SBAS_FULL[] = "SBAS";
const char DESKTOP_TEXT_GNSS_SYSTEM_IMES_FULL[] = "IMES";
const char DESKTOP_TEXT_GNSS_SYSTEM_UNKNOWN_FULL[] = "UNK";
const char DESKTOP_TEXT_GNSS_COMPASS_NORTH[] = "N";
const char DESKTOP_TEXT_GNSS_COMPASS_EAST[] = "E";
const char DESKTOP_TEXT_GNSS_COMPASS_SOUTH[] = "S";
const char DESKTOP_TEXT_GNSS_COMPASS_WEST[] = "W";
const char DESKTOP_TEXT_GNSS_TRACKED[] = "已跟踪";
const char DESKTOP_TEXT_GNSS_VISIBLE[] = "可见";
const char DESKTOP_TEXT_GNSS_SETTINGS_ENABLED[] = "启用";
const char DESKTOP_TEXT_GNSS_SETTINGS_UPDATE_INTERVAL[] = "更新周期";
const char DESKTOP_TEXT_GNSS_SETTINGS_MIN_ACTIVE[] = "最短工作";
const char DESKTOP_TEXT_GNSS_SETTINGS_NAV_MODE[] = "导航模式";
const char DESKTOP_TEXT_GNSS_SETTINGS_FIX_RATE[] = "定位频率";
const char DESKTOP_TEXT_GNSS_SETTINGS_SYSTEM[] = "系统";
const char DESKTOP_TEXT_GNSS_SETTINGS_GPS[] = "GPS";
const char DESKTOP_TEXT_GNSS_SETTINGS_GLONASS[] = "GLONASS";
const char DESKTOP_TEXT_GNSS_SETTINGS_GALILEO[] = "Galileo";
const char DESKTOP_TEXT_GNSS_SETTINGS_BEIDOU[] = "BeiDou";
const char DESKTOP_TEXT_GNSS_SETTINGS_QZSS[] = "QZSS";
const char DESKTOP_TEXT_GNSS_SETTINGS_IRNSS[] = "IRNSS";
const char DESKTOP_TEXT_GNSS_SETTINGS_SBAS[] = "SBAS";
const char DESKTOP_TEXT_GNSS_SETTINGS_IMES[] = "IMES";
const char DESKTOP_TEXT_GNSS_SETTINGS_TIME_SYNC[] = "时间同步";
const char DESKTOP_TEXT_GNSS_SETTINGS_ELECTRONIC_COMPASS[] = "电子罗盘";
const char *const DESKTOP_TEXT_GNSS_NAV_MODE_VALUES[DESKTOP_TEXT_GNSS_NAV_MODE_COUNT] = {
	"零",
	"低",
	"均衡",
	"高",
};
const char *const DESKTOP_TEXT_GNSS_FIX_RATE_VALUES[DESKTOP_TEXT_GNSS_FIX_RATE_COUNT] = {
	"1Hz",
	"2Hz",
	"4Hz",
	"5Hz",
	"10Hz",
};
const char *const DESKTOP_TEXT_GNSS_SYSTEM_MODE_VALUES[DESKTOP_TEXT_GNSS_SYSTEM_MODE_COUNT] = {
	"全部",
	"自定义",
};
const char DESKTOP_TEXT_GNSS_HEADER_UPDATE_INTERVAL_MS[] = "更新周期 (ms)";
const char DESKTOP_TEXT_GNSS_HEADER_MIN_ACTIVE_MS[] = "最短工作 (ms)";

const char DESKTOP_TEXT_GNSS_ACQUISITION_NOW[] = "立即定位";
const char DESKTOP_TEXT_GNSS_ACQUISITION_PROCESSING[] = "正在定位";
const char DESKTOP_TEXT_GNSS_FAILED[] = "GNSS 失败";
const char DESKTOP_TEXT_GNSS_SATELLITES_RELOAD[] = "卫星已重载";
const char DESKTOP_TEXT_GNSS_NO_SATELLITES[] = "无卫星";
const char DESKTOP_TEXT_GNSS_RELOAD_FAILED[] = "重载失败";

const char DESKTOP_TEXT_LAUNCHER_START_FAILED_FORMAT[] = "启动失败 (%d)";
const char DESKTOP_TEXT_LAUNCHER_CLEANUP_FAILED_FORMAT[] = "应用关闭失败 (%d)";
const char DESKTOP_TEXT_LAUNCHER_ACTION_DELETE[] = "删除";
const char DESKTOP_TEXT_LAUNCHER_ACTION_PROPERTIES[] = "属性";
const char DESKTOP_TEXT_LAUNCHER_DELETE_TITLE[] = "删除应用?";
const char DESKTOP_TEXT_LAUNCHER_DELETED[] = "已删除";
const char DESKTOP_TEXT_LAUNCHER_DELETE_FAILED_FORMAT[] = "删除失败 (%d)";
const char DESKTOP_TEXT_LAUNCHER_PROPERTIES_FAILED_FORMAT[] = "读取属性失败 (%d)";

const char DESKTOP_TEXT_MESHCORE_ADVERT[] = "广播";
const char DESKTOP_TEXT_MESHCORE_ADVERT_SELECT_TEXT[] = "通过泛洪广播?";
const char DESKTOP_TEXT_MESHCORE_ADVERT_BUTTON_FLOOD[] = "泛洪";
const char DESKTOP_TEXT_MESHCORE_ADVERT_BUTTON_ZEROHOP[] = "零跳";
const char DESKTOP_TEXT_MESHCORE_LOCAL_ADVERT_QUEUED[] = "零跳广播已排队.";
const char DESKTOP_TEXT_MESHCORE_FLOOD_ADVERT_QUEUED[] = "泛洪广播已排队.";
const char DESKTOP_TEXT_MESHCORE_MENU_RADIO_PRESET[] = "无线电预设";
const char DESKTOP_TEXT_MESHCORE_MENU_CHANNELS[] = "频道";
const char DESKTOP_TEXT_MESHCORE_CHANNELS_TITLE[] = "频道";
const char DESKTOP_TEXT_MESHCORE_CHANNELS_EMPTY[] = "(无频道)";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_NAME[] = "名称";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ROLE[] = "角色";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_PUBLIC_KEY[] = "公钥";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_MULTI_ACKS[] = "多重 ACK";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADVERT_POSITION[] = "广播位置";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_PATH_HASH_SIZE[] = "路径哈希长度";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_CLIENT_REPEAT[] = "客户端中继";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_OVERWRITE[] = "淘汰最旧";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_CHAT[] = "自动添加聊天";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_REPEATER[] = "自动添加中继";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_ROOM[] = "自动添加房间";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_SENSOR[] = "自动添加传感器";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADD_CONTACT_HOPS_LIMIT[] = "跳数限制";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_CONTACT_ADD_POLICY[] = "添加策略";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_CONTACT_ADD_POLICY_TITLE[] = "联系人添加策略";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_FORWARDING[] = "转发";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_FORWARDING_TITLE[] = "转发";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE[] = "遥测";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_TITLE[] = "遥测模式";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_BASE[] = "基础";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_LOCAT[] = "位置";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_TELEMETRY_MODE_ENVIRONMENT[] = "环境";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_TX_DELAY_FACTOR[] = "发送延时";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_DIRECT_TX_DELAY_FACTOR[] = "直发延时";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_DISABLE_FWD[] = "禁用转发";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_LOOP_DETECT[] = "环路检测";
const char *const DESKTOP_TEXT_MESHCORE_LOOP_DETECT_VALUES
	[DESKTOP_TEXT_MESHCORE_LOOP_DETECT_COUNT] = {
	DESKTOP_TEXT_COMMON_OFF,
	"最低",
	"适中",
	"严格",
};
const char DESKTOP_TEXT_MESHCORE_SETTINGS_FLOOD_MAX[] = "最大泛洪数";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_ADVERT_INTERVAL[] = "广播间隔";
const char DESKTOP_TEXT_MESHCORE_SETTINGS_FLOOD_ADVERT_INTERVAL[] = "泛洪广播间隔";
const char DESKTOP_TEXT_MESHCORE_RADIO_PRESET_TITLE[] = "无线电预设";
const char DESKTOP_TEXT_MESHCORE_CUSTOM[] = "自定义";
const char *const DESKTOP_TEXT_MESHCORE_RADIO_PRESET_NAME_VALUES
	[DESKTOP_TEXT_MESHCORE_RADIO_PRESET_COUNT] = {
	"VN920(窄带)",
	"AU915",
	"AU916(窄带)",
	"AU923(SA, WA)",
	"AU923+(QLD)",
	"EU869(窄带)",
	"CZ869(窄带)",
	"EU433(远距)",
	"NZ917",
	"NZ917+(窄带)",
	"PT433",
	"PT869",
	"CH869",
	"US910(推荐)",
};
const char *const DESKTOP_TEXT_MESHCORE_RADIO_PRESET_SHORT_VALUES
	[DESKTOP_TEXT_MESHCORE_RADIO_PRESET_COUNT] = {
	"VN920",
	"AU915",
	"AU916",
	"AU923",
	"AU923+",
	"EU869",
	"CZ869",
	"EU433",
	"NZ917",
	"NZ917+",
	"PT433",
	"PT869",
	"CH869",
	"US910",
};
const char DESKTOP_TEXT_MESHCORE_RADIO_PRESET_CONFIRM_TITLE[] = "应用预设";
const char DESKTOP_TEXT_MESHCORE_RADIO_PRESET_DETAIL_FORMAT[] =
	"%s\n频率: %u.%03u MHz\n速率: %u.%03u kHz\nSF: %u\nCR: %u\n\n";
const char DESKTOP_TEXT_MESHCORE_ACTION_RESET[] = "> 重置";
const char *const DESKTOP_TEXT_MESHCORE_ROLE_VALUES[DESKTOP_TEXT_MESHCORE_ROLE_COUNT] = {
	DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_CLIENT,
	DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_REPEATER,
	DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_ROOM,
	DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_SENSOR,
};
const char DESKTOP_TEXT_MESHCORE_CHANNEL_SETTINGS_SECRET[] = "密钥";
const char DESKTOP_TEXT_MESHCORE_CHANNEL_SETTINGS_NAME[] = "名称";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_MULTI_ACKS[] = "多重 ACK";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_FLOOD_MAX[] = "最大泛洪数(1-64)";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_CONTACT_ADD_HOPS_LIMIT[] = "跳数限制(0-63)";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_TX_DELAY_FACTOR[] = "发送延时 x100(0 - 200)";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_DIRECT_TX_DELAY_FACTOR[] = "直发延时 x100 (0 - 200)";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_ADVERT_INTERVAL[] = "广播间隔 (s)";
const char DESKTOP_TEXT_MESHCORE_NUMBER_INPUT_FLOOD_ADVERT_INTERVAL[] = "泛洪广播 (s)";
const char DESKTOP_TEXT_MESHCORE_PUBLIC_KEY_TITLE[] = "公钥";
const char DESKTOP_TEXT_MESHCORE_CHANNEL_SECRET_TITLE[] = "频道密钥";
const char DESKTOP_TEXT_MESHCORE_CHANNEL_QRCODE_BUTTON[] = "二维码";
const char DESKTOP_TEXT_MESHCORE_RESET_CONFIRM_TITLE[] = "重置";
const char DESKTOP_TEXT_MESHCORE_RESET_CONFIRM_TEXT[] =
	"重置 MeshCore? 其他节点\n会将本节点视为新设备.";
const char DESKTOP_TEXT_MESHCORE_RESET_DONE[] = "MeshCore 配置已重置.";
const char DESKTOP_TEXT_MESHCORE_TELEMETRY_MODE_DENY[] = "禁用";
const char DESKTOP_TEXT_MESHCORE_TELEMETRY_MODE_ALL[] = "启用";

const char DESKTOP_TEXT_MESSAGES_SENT[] = "已发送";
const char DESKTOP_TEXT_MESSAGES_SENT_MESSAGE[] = "消息已发送.";
const char DESKTOP_TEXT_MESSAGES_SEND_FAILED[] = "发送失败";
const char DESKTOP_TEXT_MESSAGES_SEND_FAILED_MESSAGE[] = "发送失败, 请重试.";
const char DESKTOP_TEXT_MESSAGES_INBOX[] = "收件箱";
const char DESKTOP_TEXT_MESSAGES_NEW_MESSAGE[] = "新消息";
const char DESKTOP_TEXT_MESSAGES_SELECT_TARGET[] = "选择目标";
const char DESKTOP_TEXT_MESSAGES_LOADING[] = "加载中...";
const char DESKTOP_TEXT_MESSAGES_NO_MORE_MESSAGES[] = "(没有更多消息)";
const char DESKTOP_TEXT_MESSAGES_NO_TARGET[] = "(无目标)";
const char DESKTOP_TEXT_MESSAGES_INBOX_ROW_FORMAT[] = "%s %s";
const char DESKTOP_TEXT_MESSAGES_LABEL_TO[] = "收件人";
const char DESKTOP_TEXT_MESSAGES_LABEL_ROUTE[] = "路由";
const char DESKTOP_TEXT_MESSAGES_LABEL_CONTENT[] = "内容";
const char DESKTOP_TEXT_MESSAGES_LABEL_EDIT_CONTENT[] = "编辑内容";
const char DESKTOP_TEXT_MESSAGES_ACTION_SEND[] = "> 发送";
const char DESKTOP_TEXT_MESSAGES_CUSTOM[] = "自定义";
const char DESKTOP_TEXT_MESSAGES_DETAIL_NO_MESSAGE[] = "无消息";
const char DESKTOP_TEXT_MESSAGES_CHANNEL_SHORT[] = "CH@";
const char DESKTOP_TEXT_MESSAGES_PERSON_SHORT[] = "DM@";
const char DESKTOP_TEXT_MESSAGES_FLOOD_SHORT[] = "FL@";
const char *const DESKTOP_TEXT_MESSAGES_ROUTE_VALUES[DESKTOP_TEXT_MESSAGES_ROUTE_COUNT] = {
	"泛洪",
	"直发",
};
const char DESKTOP_TEXT_MESSAGES_TIME_AGO_NOW[] = "刚刚";
const char DESKTOP_TEXT_MESSAGES_TIME_AGO_MIN_FORMAT[] = "%um";
const char DESKTOP_TEXT_MESSAGES_TIME_AGO_HOUR_FORMAT[] = "%uh";
const char DESKTOP_TEXT_MESSAGES_TIME_AGO_DAY_FORMAT[] = "%ud";
const char DESKTOP_TEXT_MESSAGES_TARGET_CHANNEL_FORMAT[] = "频道 %s (%u)";
const char DESKTOP_TEXT_MESSAGES_TARGET_CONTACT_FORMAT[] = "联系人 %s (%02X%02X%02X)";
const char *const DESKTOP_TEXT_MESSAGES_CANNED_VALUES[DESKTOP_TEXT_MESSAGES_CANNED_COUNT] = {
	"OK",
	"我在路上",
	"需要帮助",
	"你在哪里?",
	"电量低",
};
const char *const DESKTOP_TEXT_MESSAGES_CONTENT_VALUES[DESKTOP_TEXT_MESSAGES_CONTENT_OPTION_COUNT] = {
	"OK",
	"我在路上",
	"需要帮助",
	"你在哪里?",
	"电量低",
	DESKTOP_TEXT_MESSAGES_CUSTOM,
};

const char DESKTOP_TEXT_NODES_SENT[] = "已发送";
const char DESKTOP_TEXT_NODES_REQUEST_SENT[] = "请求已发送.";
const char DESKTOP_TEXT_NODES_REQUESTING[] = "请求中...";
const char DESKTOP_TEXT_NODES_REQUEST_ERROR_BUSY_RETRY_LATER[] = "繁忙, 请稍后重试";
const char DESKTOP_TEXT_NODES_REQUEST_ERROR_FAILURE[] = "请求失败";
const char DESKTOP_TEXT_NODES_REQUEST_ERROR_NEIGHBOR_NOT_ALLOW[] = "邻居不允许";
const char DESKTOP_TEXT_NODES_DELETED[] = "已删除";
const char DESKTOP_TEXT_NODES_NODE_DELETED[] = "节点已删除.";
const char DESKTOP_TEXT_NODES_DISCOVER_PATH_REQUEST_SENT[] = "路径发现已发送.";
const char DESKTOP_TEXT_NODES_TRACE_PATH_REQUEST_SENT[] = "路径追踪已发送.";
const char DESKTOP_TEXT_NODES_BROADCAST_REQUEST_SENT[] = "广播已发送.";
const char DESKTOP_TEXT_NODES_NODE[] = "节点";
const char DESKTOP_TEXT_NODES_NO_NODE[] = "(无节点)";
const char DESKTOP_TEXT_NODES_NO_NODES[] = "(无节点)";
const char DESKTOP_TEXT_NODES_MENU_ALIAS[] = "别名";
const char DESKTOP_TEXT_NODES_MENU_NAME[] = "名称";
const char DESKTOP_TEXT_NODES_MENU_ROLE[] = "角色";
const char DESKTOP_TEXT_NODES_MENU_PUBLIC_KEY[] = "公钥";
const char DESKTOP_TEXT_NODES_MENU_PERMISSION[] = "权限";
const char DESKTOP_TEXT_NODES_MENU_BROADCAST[] = "> 广播";
const char DESKTOP_TEXT_NODES_MENU_BATTERY[] = "电池";
const char DESKTOP_TEXT_NODES_MENU_LATITUDE[] = "纬度";
const char DESKTOP_TEXT_NODES_MENU_LONGITUDE[] = "经度";
const char DESKTOP_TEXT_NODES_MENU_TELEMETRY[] = "遥测";
const char DESKTOP_TEXT_NODES_MENU_DISCOVER_PATH[] = "路径";
const char DESKTOP_TEXT_NODES_MENU_TRACE_PATH[] = "路径追踪";
const char DESKTOP_TEXT_NODES_MENU_DELETE[] = "> 删除";
const char DESKTOP_TEXT_NODES_PERMISSION_TITLE[] = "遥测权限";
const char DESKTOP_TEXT_NODES_PERMISSION_BASE[] = "基础";
const char DESKTOP_TEXT_NODES_PERMISSION_LOCATION[] = "位置";
const char DESKTOP_TEXT_NODES_PERMISSION_ENVIRONMENT[] = "环境";
const char DESKTOP_TEXT_NODES_ROLE_REPEATER[] = "中继";
const char DESKTOP_TEXT_NODES_ROLE_CLIENT[] = "客户端";
const char DESKTOP_TEXT_NODES_TITLE_DISCOVER_PATH[] = "路径";
const char DESKTOP_TEXT_NODES_TITLE_TRACE_PATH[] = "路径追踪";
const char DESKTOP_TEXT_NODES_BUTTON_REDISCOVER[] = "路径发现";
const char DESKTOP_TEXT_NODES_BUTTON_RETRACE[] = "追踪";
const char DESKTOP_TEXT_NODES_DISCOVERING[] = "发现中...";
const char DESKTOP_TEXT_NODES_TRACING[] = "追踪中...";
const char DESKTOP_TEXT_NODES_STATUS_TRACE_SUCCESS[] = "成功";
const char DESKTOP_TEXT_NODES_STATUS_TRACE_WAITING[] = "等待";
const char DESKTOP_TEXT_NODES_STATUS_TRACE_NONE[] = "--";
const char DESKTOP_TEXT_NODES_ACTION_CONFIRM_DELETE_HEADER[] = "删除节点?";
const char DESKTOP_TEXT_NODES_ACTION_CONFIRM_DELETE_TEXT_FORMAT[] =
	"删除节点:\n%s";
const char DESKTOP_TEXT_NODES_DISCOVER_READY_TEXT_FORMAT[] =
	"节点: %s\n路径: %s";
const char DESKTOP_TEXT_NODES_TRACE_PATH_TEXT_FORMAT[] =
	"节点: %s\n路径: %s\n状态: %s";
const char DESKTOP_TEXT_NODES_TELEMETRY_TITLE[] = "遥测";
const char DESKTOP_TEXT_NODES_TELEMETRY_NO_NODE[] = "(无节点)";
const char DESKTOP_TEXT_NODES_PUBLIC_KEY_TITLE[] = "公钥";
const char DESKTOP_TEXT_NODES_TIME_AGO_NOW[] = "刚刚";
const char DESKTOP_TEXT_NODES_TIME_AGO_OVER_7D[] = "7天+";
const char DESKTOP_TEXT_NODES_TIME_AGO_MIN_FORMAT[] = "%um";
const char DESKTOP_TEXT_NODES_TIME_AGO_HOUR_FORMAT[] = "%uh";
const char DESKTOP_TEXT_NODES_TIME_AGO_DAY_FORMAT[] = "%ud";
const char DESKTOP_TEXT_NODES_DASH[] = "-";
const char DESKTOP_TEXT_NODES_NEIGHBOR[] = "邻居";

const char DESKTOP_TEXT_TELEMETRY_READINGS[] = "读数";
const char DESKTOP_TEXT_TELEMETRY_TRIGGER_SAMPLE[] = "触发采样";
const char DESKTOP_TEXT_TELEMETRY_SETTINGS_ENABLED[] = "启用";
const char DESKTOP_TEXT_TELEMETRY_SETTINGS_INTERVAL[] = "周期";
const char DESKTOP_TEXT_TELEMETRY_HEADER_INTERVAL_MS[] = "采样周期 (ms)";
const char DESKTOP_TEXT_TELEMETRY_NO_READINGS[] = "(无读数)";
const char DESKTOP_TEXT_TELEMETRY_NO_DATA[] = "暂无数据";
const char DESKTOP_TEXT_TELEMETRY_SAMPLE_TRIGGERED[] = "已触发采样";
const char DESKTOP_TEXT_TELEMETRY_SAMPLE_DISABLED[] = "遥测已禁用";
const char DESKTOP_TEXT_TELEMETRY_SAMPLE_FAILED[] = "采样失败";
const char DESKTOP_TEXT_TELEMETRY_OPEN_FAILED[] = "无法打开";
const char DESKTOP_TEXT_TELEMETRY_READING_DETAIL_FORMAT[] =
	"传感器:\n"
	"  %s\n"
	"频道:\n"
	"  %s (%u)\n"
	"参数:\n"
	"  %s\n"
	"数值:\n"
	"  %s\n"
	"采样:\n"
	"  运行:   %u ms\n"
	"  时间:   %s";

const char DESKTOP_TEXT_POWER_SETTINGS_LOW_VOLTAGE_TIMEOUT[] = "低电压";
const char DESKTOP_TEXT_POWER_SETTINGS_LOSING_POWER_TIMEOUT[] = "掉电";
const char DESKTOP_TEXT_POWER_SETTINGS_NO_CONNECTION_TIMEOUT[] = "无连接";
const char DESKTOP_TEXT_POWER_VALUE_SECONDS_FORMAT[] = "%us";
const char DESKTOP_TEXT_POWER_VALUE_TEMPERATURE_FORMAT[] = "%s%u.%uC";

const char DESKTOP_TEXT_SYSTEM_MENU_INFORMATION[] = "信息";
const char DESKTOP_TEXT_SYSTEM_MENU_IDENTITY[] = "身份";
const char DESKTOP_TEXT_SYSTEM_MENU_HARDWARE[] = "硬件";
const char DESKTOP_TEXT_SYSTEM_MENU_FIRMWARE[] = "固件";
const char DESKTOP_TEXT_SYSTEM_MENU_RUNTIME[] = "运行状态";
const char DESKTOP_TEXT_SYSTEM_MENU_DEVICES[] = "设备";
const char DESKTOP_TEXT_SYSTEM_MENU_INDICATOR[] = "指示器";
const char DESKTOP_TEXT_INDICATOR_TITLE[] = "指示器";
const char DESKTOP_TEXT_INDICATOR_LIGHT[] = "灯光";
const char DESKTOP_TEXT_INDICATOR_HEARTBEAT[] = "心跳";
const char DESKTOP_TEXT_INDICATOR_BUZZER[] = "蜂鸣器";
const char DESKTOP_TEXT_INDICATOR_DM[] = "DM";
const char DESKTOP_TEXT_INDICATOR_CHANNEL[] = "频道";
const char DESKTOP_TEXT_INDICATOR_SYSTEM[] = "系统";
const char DESKTOP_TEXT_SYSTEM_INFO_IDENTITY_FORMAT[] =
	"名称:\n"
	"  %s\n"
	"制造商:\n"
	"  %s\n"
	"型号:\n"
	"  %s\n"
	"序列号:\n"
	"  %s";
const char DESKTOP_TEXT_SYSTEM_INFO_HARDWARE_FORMAT[] =
	"MCU:\n"
	"  %s\n"
	"Flash:\n"
	"  %u kb\n"
	"RAM:\n"
	"  %u kb";
const char DESKTOP_TEXT_SYSTEM_INFO_HARDWARE_BLUETOOTH_FORMAT[] =
	"MCU:\n"
	"  %s\n"
	"Flash:\n"
	"  %u kb\n"
	"RAM:\n"
	"  %u kb\n"
	"蓝牙地址:\n"
	"  %s";
const char DESKTOP_TEXT_SYSTEM_INFO_FIRMWARE_FORMAT[] =
	"应用版本:\n"
	"  %s\n"
	"构建版本:\n"
	"  %s\n"
	"内核版本:\n"
	"  Zephyr %s";
const char DESKTOP_TEXT_SYSTEM_INFO_RUNTIME_FORMAT[] =
	"运行时间:\n"
	"  %llu ms\n"
	"周期数:\n"
	"  %llu\n"
	"重置原因:\n"
	"  %s\n"
	"堆空闲:\n"
	"  %s\n"
	"堆已用:\n"
	"  %s\n"
	"ZUI 堆空闲:\n"
	"  %s\n"
	"ZUI 堆已用:\n"
	"  %s";
const char DESKTOP_TEXT_SYSTEM_DEVICE_STATE_READY[] = "就绪";
const char DESKTOP_TEXT_SYSTEM_DEVICE_STATE_DISABLED[] = "禁用";
const char DESKTOP_TEXT_SYSTEM_DEVICE_USAGE_FORMAT[] = "- %s (%s, 使用=%d)\n";
const char DESKTOP_TEXT_SYSTEM_DEVICE_FORMAT[] = "- %s (%s)\n";

const char DESKTOP_TEXT_RADIO_PACKET[] = "数据包";
const char DESKTOP_TEXT_RADIO_CONTINUOUS_WAVE[] = "连续波";
const char DESKTOP_TEXT_RADIO_NOISE_ANALYZER[] = "噪声分析";
const char DESKTOP_TEXT_RADIO_CALIBRATE_NF[] = "校准 NF";
const char DESKTOP_TEXT_RADIO_AGC_RESET[] = "重置 AGC";
const char DESKTOP_TEXT_RADIO_SETTINGS[] = "设置";
const char DESKTOP_TEXT_RADIO_DISABLED[] = "无线电已禁用";
const char DESKTOP_TEXT_RADIO_CALIBRATING[] = "校准中";
const char DESKTOP_TEXT_RADIO_RX_ONLY_MODE[] = "仅接收模式";

const char DESKTOP_TEXT_RADIO_SEND_AS_TEXT[] = "发送文本";
const char DESKTOP_TEXT_RADIO_SEND_AS_HEX[] = "发送十六进制";
const char DESKTOP_TEXT_RADIO_PACKET_CAPTURE[] = "数据包捕获";

const char DESKTOP_TEXT_RADIO_CAPTURE[] = "捕获";
const char DESKTOP_TEXT_RADIO_RSSI[] = "RSSI";
const char DESKTOP_TEXT_RADIO_SNR[] = "SNR";
const char DESKTOP_TEXT_RADIO_LEN[] = "LEN";
const char DESKTOP_TEXT_RADIO_HEX[] = "Hex";
const char DESKTOP_TEXT_RADIO_TEXT[] = "文本";
const char DESKTOP_TEXT_RADIO_EMPTY[] = "(空)";
const char DESKTOP_TEXT_RADIO_DASH[] = "--";

const char DESKTOP_TEXT_RADIO_NOISE[] = "噪声";
const char DESKTOP_TEXT_RADIO_DBM[] = "dBm";
const char DESKTOP_TEXT_RADIO_FORMAT_MIN_MAX[] = "最小 %d | 最大 %d";
const char DESKTOP_TEXT_RADIO_MIN_MAX_DASH[] = "最小 -- | 最大 --";
const char DESKTOP_TEXT_RADIO_RX_UNKNOWN[] = "RX?";
const char DESKTOP_TEXT_RADIO_NA[] = "N/A";
const char DESKTOP_TEXT_RADIO_FORMAT_NF_STATUS[] = "NF %d | %s";
const char DESKTOP_TEXT_RADIO_FORMAT_NF_DASH_STATUS[] = "NF -- | %s";
const char DESKTOP_TEXT_RADIO_ACT[] = "ACT";
const char DESKTOP_TEXT_RADIO_QUIET[] = "安静";

const char DESKTOP_TEXT_RADIO_SETTINGS_ENABLED[] = "启用";
const char DESKTOP_TEXT_RADIO_SETTINGS_RX_ONLY[] = "仅接收";
const char DESKTOP_TEXT_RADIO_SETTINGS_FREQUENCY[] = "频率";
const char DESKTOP_TEXT_RADIO_SETTINGS_BANDWIDTH[] = "带宽";
const char DESKTOP_TEXT_RADIO_SETTINGS_DATA_RATE[] = "数据率";
const char DESKTOP_TEXT_RADIO_SETTINGS_CODING_RATE[] = "编码率";
const char DESKTOP_TEXT_RADIO_SETTINGS_PREAMBLE[] = "前导码";
const char DESKTOP_TEXT_RADIO_SETTINGS_TX_POWER[] = "发射功率";
const char DESKTOP_TEXT_RADIO_SETTINGS_PACKET_CRC[] = "数据包 CRC";
const char DESKTOP_TEXT_RADIO_SETTINGS_RX_BOOSTED[] = "接收增强";
const char DESKTOP_TEXT_RADIO_SETTINGS_DUTY_CYCLE[] = "占空比";
const char DESKTOP_TEXT_RADIO_SETTINGS_DUTY_RX_TIME[] = "接收时长";
const char DESKTOP_TEXT_RADIO_SETTINGS_DUTY_SLEEP_TIME[] = "休眠时长";

const char DESKTOP_TEXT_RADIO_CW_TX_POWER[] = "发射功率";
const char DESKTOP_TEXT_RADIO_CW_DURATION[] = "时长";
const char DESKTOP_TEXT_RADIO_CW_EXECUTE[] = "> 执行";

const char DESKTOP_TEXT_RADIO_HEADER_FREQUENCY_HZ[] = "频率 (Hz)";
const char DESKTOP_TEXT_RADIO_HEADER_PREAMBLE[] = "前导码";
const char DESKTOP_TEXT_RADIO_HEADER_DUTY_RX_MS[] = "接收时长 (ms)";
const char DESKTOP_TEXT_RADIO_HEADER_DUTY_SLEEP_MS[] = "休眠时长 (ms)";

const char DESKTOP_TEXT_RADIO_REJECTED[] = "已拒绝";
const char DESKTOP_TEXT_RADIO_EXECUTING[] = "执行中";
const char DESKTOP_TEXT_RADIO_FINISHED[] = "已完成";

const char DESKTOP_TEXT_RADIO_FORMAT_ERROR_CODE[] = "错误码 (%d)";
const char DESKTOP_TEXT_RADIO_FORMAT_LEN_TOA[] = "长度: %u 字节, ToA: %u ms";
const char DESKTOP_TEXT_RADIO_FORMAT_TEXT_MESSAGE_HEADER[] = "文本消息 (%u/%u)";
const char DESKTOP_TEXT_RADIO_FORMAT_HEX_PAYLOAD_HEADER[] = "十六进制载荷 (%u/%u)";
const char DESKTOP_TEXT_RADIO_FORMAT_U_MS[] = "%ums";

const char *const DESKTOP_TEXT_RADIO_BW_VALUES[DESKTOP_TEXT_RADIO_BW_COUNT] = {
	"7.8 kHz",
	"10.4 kHz",
	"15.6 kHz",
	"20.8 kHz",
	"31.25 kHz",
	"41.7 kHz",
	"62.5 kHz",
	"125 kHz",
	"250 kHz",
	"500 kHz",
};

const char DESKTOP_TEXT_VIEW_MENU_INVALID_APP[] = "(无效)";
const char DESKTOP_TEXT_VIEW_POWER_SLEEP[] = "休眠";
const char DESKTOP_TEXT_VIEW_POWER_SHUTDOWN[] = "关机";
const char DESKTOP_TEXT_VIEW_POWER_REBOOT[] = "重启";
const char DESKTOP_TEXT_VIEW_POWER_INVALID[] = "(无效)";
const char DESKTOP_TEXT_VIEW_POWER_SLEEP_SELECTED[] = "已选择休眠";
const char DESKTOP_TEXT_VIEW_POWER_SHUTDOWN_SELECTED[] = "已选择关机";
const char DESKTOP_TEXT_VIEW_POWER_REBOOT_SELECTED[] = "已选择重启";

const char *const DESKTOP_TEXT_WIDGET_CLOCK_DAY_VALUES[DESKTOP_TEXT_WIDGET_CLOCK_DAY_COUNT] = {
	"日",
	"一",
	"二",
	"三",
	"四",
	"五",
	"六",
};
const char DESKTOP_TEXT_WIDGET_CLOCK_MERIDIEM_AM[] = "A";
const char DESKTOP_TEXT_WIDGET_CLOCK_MERIDIEM_PM[] = "P";
const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_HMS[] = "--";
const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_DAY[] = "---";
const char DESKTOP_TEXT_WIDGET_CLOCK_PLACEHOLDER_DATE[] = "--.--";
const char DESKTOP_TEXT_WIDGET_CLOCK_SYNC[] = "已同步";
const char DESKTOP_TEXT_WIDGET_CLOCK_UNSYNC[] = "未同步";

const char *const DESKTOP_TEXT_WIDGET_COMPASS_DIRECTION_VALUES
	[DESKTOP_TEXT_WIDGET_COMPASS_DIRECTION_COUNT] = {
	"N",
	"NE",
	"E",
	"SE",
	"S",
	"SW",
	"W",
	"NW",
};
const char DESKTOP_TEXT_WIDGET_COMPASS_PLACEHOLDER_HEADING[] = "---";
const char DESKTOP_TEXT_WIDGET_COMPASS_PLACEHOLDER_DIRECTION[] = "--";
const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_LABEL[] = "精度";
const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_UNAVAILABLE[] = "--";
const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_UNRELIABLE[] = "不可靠";
const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_LOW[] = "低";
const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_MEDIUM[] = "中";
const char DESKTOP_TEXT_WIDGET_COMPASS_ACCURACY_HIGH[] = "高";
const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_OFF[] = "关";
const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_WAIT[] = "等待";
const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_CALIBRATE[] = "校准";
const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_LEVEL[] = "水平";
const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_OK[] = "正常";
const char DESKTOP_TEXT_WIDGET_COMPASS_STATUS_ERROR[] = "错误";
const char DESKTOP_TEXT_WIDGET_COMPASS_CALIBRATION_TITLE[] = "罗盘需要校准";
const char DESKTOP_TEXT_WIDGET_COMPASS_CALIBRATION_ACTION[] = "请画 8 字";

const char DESKTOP_TEXT_WIDGET_INFO_ICON_INFO[] = "i";
const char DESKTOP_TEXT_WIDGET_INFO_LABEL_UPTIME[] = "运行时间";
const char DESKTOP_TEXT_WIDGET_INFO_LABEL_VERSION[] = "版本";
const char DESKTOP_TEXT_WIDGET_INFO_LABEL_SN[] = "SN";
const char DESKTOP_TEXT_WIDGET_INFO_PLACEHOLDER_DEVICE[] = "--";
const char DESKTOP_TEXT_WIDGET_INFO_PLACEHOLDER_UPTIME[] = "0d0h0m";
const char DESKTOP_TEXT_WIDGET_INFO_PLACEHOLDER_VERSION[] = "--";
const char DESKTOP_TEXT_WIDGET_INFO_SERIAL_UNKNOWN[] = "未知";
const char DESKTOP_TEXT_WIDGET_INFO_UPTIME_FORMAT[] = "%llu天%llu时%llu分";

const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE[] = "客户端";
const char DESKTOP_TEXT_WIDGET_MESHCORE_SYNC_WORD_PRIVATE[] = "PR";
const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_CLIENT[] = "聊天";
const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_REPEATER[] = "中继";
const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_ROOM[] = "房间";
const char DESKTOP_TEXT_WIDGET_MESHCORE_ROLE_SENSOR[] = "传感器";
const char DESKTOP_TEXT_WIDGET_MESHCORE_VERSION[] = "v1.0";

const char DESKTOP_TEXT_WIDGET_MESSAGES_NO_MORE_MESSAGES[] = "没有更多消息";
const char DESKTOP_TEXT_WIDGET_MESSAGES_EMPTY[] = "空";
const char DESKTOP_TEXT_WIDGET_MESSAGES_DIRECT[] = "DM";
const char DESKTOP_TEXT_WIDGET_MESSAGES_CHANNEL[] = "CH";
const char DESKTOP_TEXT_WIDGET_MESSAGES_FLOOD[] = "FL";
const char DESKTOP_TEXT_WIDGET_MESSAGES_SELECTED_LINE_FORMAT[] = "> %s";

const char DESKTOP_TEXT_WIDGET_NODES_UNKNOWN_NAME[] = "???";
const char DESKTOP_TEXT_WIDGET_NODES_EMPTY[] = "空";
const char DESKTOP_TEXT_WIDGET_NODES_CLI[] = "CLI";
const char DESKTOP_TEXT_WIDGET_NODES_RPT[] = "RPT";
const char DESKTOP_TEXT_WIDGET_NODES_BROADCAST[] = "广播";
const char DESKTOP_TEXT_WIDGET_NODES_CONTACT_FORMAT[] = "%s@%s";
const char DESKTOP_TEXT_WIDGET_NODES_ROLE_COUNTS_FORMAT[] = "%s %u / %s %u";

const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_DIR[] = "-";
const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_DEG[] = "---";
const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_MIN[] = "--.---'";
const char DESKTOP_TEXT_WIDGET_POSITION_PLACEHOLDER_ALT[] = "---.-";
const char DESKTOP_TEXT_WIDGET_POSITION_LABEL_POSITION[] = "位置";
const char DESKTOP_TEXT_WIDGET_POSITION_LABEL_ALTITUDE[] = "海拔";
const char DESKTOP_TEXT_WIDGET_POSITION_UNIT_METER[] = "m";

const char DESKTOP_TEXT_WIDGET_POWER_PLACEHOLDER_SOC[] = "--%";
const char DESKTOP_TEXT_WIDGET_POWER_PLACEHOLDER_VOLTAGE[] = "--.--V";
const char DESKTOP_TEXT_WIDGET_POWER_TEMP_NC[] = "NC";
const char DESKTOP_TEXT_WIDGET_POWER_VOLTAGE_FORMAT[] = "%u.%02uV";

const char *const DESKTOP_TEXT_WIDGET_RADIO_BW_SHORT_VALUES[DESKTOP_TEXT_WIDGET_RADIO_BW_SHORT_COUNT] = {
	"7.8k",  "10.4k", "15.6k",  "20.8k", "31.25k",
	"41.7k", "62.5k", "125k",   "200k",  "250k",
	"400k",  "500k",  "800k",   "1M",    "1.6M",
};
const char DESKTOP_TEXT_WIDGET_RADIO_PLACEHOLDER_FREQUENCY[] = "---.---";
const char DESKTOP_TEXT_WIDGET_RADIO_PLACEHOLDER_VALUE[] = "--";
const char DESKTOP_TEXT_WIDGET_RADIO_LR[] = "LR";
const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_OFF[] = "关";
const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_TX[] = "TX";
const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_RX[] = "RX";
const char DESKTOP_TEXT_WIDGET_RADIO_STATUS_IDLE[] = "空闲";
const char DESKTOP_TEXT_WIDGET_RADIO_BW_KHZ_FORMAT[] = "%uk";
const char DESKTOP_TEXT_WIDGET_RADIO_TX_POWER_FORMAT[] = "%ddB";
const char DESKTOP_TEXT_WIDGET_RADIO_SF_FORMAT[] = "SF%u";
const char DESKTOP_TEXT_WIDGET_RADIO_CR_FORMAT[] = "CR%u";

const char DESKTOP_TEXT_WIDGET_TELEMETRY_STATUS_ON[] = "ON";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_STATUS_OFF[] = "关";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_NO_DATA[] = "无数据";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_BINDINGS_FORMAT[] = "%u 路";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_INTERVAL_FORMAT[] = "%us";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_AGE_FORMAT[] = "%us前";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_COUNT_FORMAT[] = "%u";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_ACCEL[] = "加速度";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_GYRO[] = "陀螺仪";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_MAGN[] = "磁场";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_DIE_TEMP[] = "芯片温度";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_AMBIENT[] = "环境温度";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_PRESS[] = "气压";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_HUMIDITY[] = "湿度";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_LIGHT[] = "灯光";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_VOLTAGE[] = "电压";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_CURRENT[] = "电流";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_BATTERY[] = "电池";
const char DESKTOP_TEXT_WIDGET_TELEMETRY_LABEL_CHANNEL[] = "频道";
const char *const
	DESKTOP_TEXT_WIDGET_TELEMETRY_AXIS_VALUES[DESKTOP_TEXT_WIDGET_TELEMETRY_AXIS_COUNT] = {
		"X",
		"Y",
		"Z",
		"W",
	};

const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_OFF[] = "关";
const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_SLEEP[] = "休眠";
const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_ACQ[] = "寻星";
const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_TRACK[] = "跟踪";
const char DESKTOP_TEXT_WIDGET_SATELLITE_STATUS_ERROR[] = "错误";
const char DESKTOP_TEXT_WIDGET_SATELLITE_LABEL_HDOP[] = "HDOP";
const char DESKTOP_TEXT_WIDGET_SATELLITE_LABEL_SATS[] = "卫星";
const char DESKTOP_TEXT_WIDGET_SATELLITE_TZ_LUT[] = "LUT";
const char DESKTOP_TEXT_WIDGET_SATELLITE_PLACEHOLDER_HDOP[] = "--";
const char DESKTOP_TEXT_WIDGET_SATELLITE_PLACEHOLDER_SATS[] = "--/--";
const char DESKTOP_TEXT_WIDGET_SATELLITE_PLACEHOLDER_UTC[] = "---- -- -- --:--:--";

const char DESKTOP_TEXT_WIDGET_USAGE_TITLE_RAM_USAGE[] = "RAM 使用率";
const char DESKTOP_TEXT_WIDGET_USAGE_LABEL_SYSTEM[] = "系统";
const char DESKTOP_TEXT_WIDGET_USAGE_LABEL_GRAPH[] = "图形";
const char DESKTOP_TEXT_WIDGET_USAGE_NOT_AVAILABLE[] = "不适用";
