#!/usr/bin/env python3
# Copyright (c) 2026 FoBE Studio
# SPDX-License-Identifier: Apache-2.0

"""Generate the selected B-style monochrome logo from the color SVG faces.

The solid faces have a two-pixel lower-right depth contour, separated by a
black pixel. Sample the rectilinear M/L/Z paths without antialiasing or dithering.
"""

import argparse
from pathlib import Path
import re
import xml.etree.ElementTree as ET

from PIL import Image


WIDTH, HEIGHT = 84, 56
DEPTH = 2
ASSET_DIR = Path(__file__).resolve().parent


def path_edges(path):
    tokens = re.findall(r"[MLZ]|-?\d+(?:\.\d+)?", path)
    if re.sub(r"[MLZ]|-?\d+(?:\.\d+)?|[\s,]+", "", path):
        raise ValueError("Only absolute M/L/Z commands are supported")
    edges = []
    first = previous = None
    index = 0
    while index < len(tokens):
        command = tokens[index]
        index += 1
        if command == "Z":
            if first is None or previous is None:
                raise ValueError("Missing subpath")
            point = first
        elif command in ("M", "L"):
            x, y = map(float, tokens[index:index + 2])
            index += 2
            point = (x, y)
        else:
            raise ValueError("Expected an explicit path command")
        if command == "M":
            if previous is not None:
                raise ValueError("Unclosed subpath")
            first = point
        else:
            if previous is None:
                raise ValueError("Missing move command")
            if previous[0] != point[0] and previous[1] != point[1]:
                raise ValueError("Expected rectilinear edges")
            edges.append((previous, point))
        previous = None if command == "Z" else point
    if previous is not None:
        raise ValueError("Unclosed subpath")
    return edges


def rasterize(source):
    root = ET.parse(source).getroot()
    ns = "{http://www.w3.org/2000/svg}"
    faces = root.find(f".//{ns}g[@id='letter-faces']")
    if faces is None or len(faces) != 7:
        raise ValueError("Expected seven letter faces")
    if any("transform" in element.attrib for element in faces.iter()):
        raise ValueError("Transforms within letter-faces are not supported")
    edges = []
    for path in faces:
        if path.tag != f"{ns}path" or path.get("fill-rule") != "evenodd":
            raise ValueError("Expected even-odd letter paths")
        edges.extend(path_edges(path.attrib["d"]))

    # Use local face coordinates, ignoring the artwork group's canvas padding.
    min_x = min(point[0] for edge in edges for point in edge)
    min_y = min(point[1] for edge in edges for point in edge)
    width = max(point[0] for edge in edges for point in edge) - min_x
    height = max(point[1] for edge in edges for point in edge) - min_y
    face_width, face_height = WIDTH - DEPTH, HEIGHT - DEPTH
    scale = min(face_width / width, face_height / height)
    offset_x = (face_width - width * scale) / 2
    edges = [tuple(((x - min_x) * scale + offset_x, (y - min_y) * scale)
                   for x, y in edge) for edge in edges]

    pixels = set()
    for y in range(face_height):
        crossings = sorted(
            a[0] for a, b in edges if min(a[1], b[1]) <= y + 0.5 < max(a[1], b[1])
        )
        if len(crossings) % 2:
            raise ValueError("Unpaired scanline crossings")
        for left, right in zip(crossings[::2], crossings[1::2]):
            for x in range(face_width):
                if left <= x + 0.5 < right:
                    pixels.add((x, y))

    # Leave a one-pixel black separation around the face, including counters.
    expanded = {(x + dx, y + dy) for x, y in pixels
                for dx, dy in ((0, 0), (1, 0), (-1, 0), (0, 1), (0, -1))}
    contour = {(x + DEPTH, y + DEPTH) for x, y in pixels} - expanded
    mask = Image.new("1", (WIDTH, HEIGHT))
    for x, y in pixels | contour:
        mask.putpixel((x, y), 255)
    return mask


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    mask = rasterize(ASSET_DIR / "meshbus-green-light.svg")
    asset = Image.new("RGBA", mask.size, "white")
    asset.putalpha(mask.convert("L"))
    asset.save(args.output_dir / "meshbus_84x56.png")

    stride = (WIDTH + 7) // 8
    data = bytearray(stride * HEIGHT)
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if mask.getpixel((x, y)):
                data[y * stride + x // 8] |= 1 << (x % 8)
    rows = ["\t" + ", ".join(f"0x{b:02x}" for b in data[i:i + stride]) + ","
            for i in range(0, len(data), stride)]
    header = (
        "/* Generated by assets/logo/generate.py; do not edit. */\n"
        # REUSE-IgnoreStart
        "/* SPDX-FileCopyrightText: FoBE Studio */\n"
        "/* SPDX-License-Identifier: Apache-2.0 */\n\n"
        # REUSE-IgnoreEnd
        "#pragma once\n\n#include <stdint.h>\n\n"
        f"#define MESHBUS_BOOT_LOGO_WIDTH {WIDTH}\n"
        f"#define MESHBUS_BOOT_LOGO_HEIGHT {HEIGHT}\n\n"
        "/* XBM: row-major, LSB first, zero-padded rows; 1 = foreground. */\n"
        "static const uint8_t meshbus_boot_logo[] = {\n" + "\n".join(rows) + "\n};\n"
    )
    (args.output_dir / "meshbus_logo.h").write_text(header)
    preview = Image.new("1", (128, 64))
    preview.paste(mask, ((128 - WIDTH) // 2, (64 - HEIGHT) // 2))
    preview.save(args.output_dir / "boot_128x64.png")
    preview.resize((512, 256), Image.Resampling.NEAREST).save(
        args.output_dir / "boot_128x64_4x.png"
    )
    print(f"Generated {WIDTH}x{HEIGHT} logo: {len(data)} bytes, XBM LSB first")


if __name__ == "__main__":
    main()
