/*
 * SPDX-FileCopyrightText: FoBE Studio
 * SPDX-License-Identifier: Apache-2.0
 *
 * Devicetree constants for Zephyr sensor channels.
 *
 * Note: Devicetree cannot reference C enums directly. This header mirrors the
 * numeric values of Zephyr's enum sensor_channel from:
 *   zephyr/include/zephyr/drivers/sensor.h
 *
 * Keep this file in sync if upstream sensor_channel changes.
 */

#ifndef MESHBUS_INCLUDE_DT_BINDINGS_SENSOR_SENSOR_CHANNEL_H_
#define MESHBUS_INCLUDE_DT_BINDINGS_SENSOR_SENSOR_CHANNEL_H_

#define SENSOR_CHAN_ACCEL_X 0
#define SENSOR_CHAN_ACCEL_Y 1
#define SENSOR_CHAN_ACCEL_Z 2
#define SENSOR_CHAN_ACCEL_XYZ 3
#define SENSOR_CHAN_GYRO_X 4
#define SENSOR_CHAN_GYRO_Y 5
#define SENSOR_CHAN_GYRO_Z 6
#define SENSOR_CHAN_GYRO_XYZ 7
#define SENSOR_CHAN_MAGN_X 8
#define SENSOR_CHAN_MAGN_Y 9
#define SENSOR_CHAN_MAGN_Z 10
#define SENSOR_CHAN_MAGN_XYZ 11
#define SENSOR_CHAN_DIE_TEMP 12
#define SENSOR_CHAN_AMBIENT_TEMP 13
#define SENSOR_CHAN_PRESS 14
#define SENSOR_CHAN_PROX 15
#define SENSOR_CHAN_HUMIDITY 16
#define SENSOR_CHAN_AMBIENT_LIGHT 17
#define SENSOR_CHAN_LIGHT 18
#define SENSOR_CHAN_IR 19
#define SENSOR_CHAN_RED 20
#define SENSOR_CHAN_GREEN 21
#define SENSOR_CHAN_BLUE 22
#define SENSOR_CHAN_ALTITUDE 23
#define SENSOR_CHAN_PM_1_0_CF 24
#define SENSOR_CHAN_PM_2_5_CF 25
#define SENSOR_CHAN_PM_10_CF 26
#define SENSOR_CHAN_PM_1_0 27
#define SENSOR_CHAN_PM_2_5 28
#define SENSOR_CHAN_PM_10 29
#define SENSOR_CHAN_PM_0_3_COUNT 30
#define SENSOR_CHAN_PM_0_5_COUNT 31
#define SENSOR_CHAN_PM_1_0_COUNT 32
#define SENSOR_CHAN_PM_2_5_COUNT 33
#define SENSOR_CHAN_PM_5_COUNT 34
#define SENSOR_CHAN_PM_10_COUNT 35
#define SENSOR_CHAN_DISTANCE 36
#define SENSOR_CHAN_CO2 37
#define SENSOR_CHAN_O2 38
#define SENSOR_CHAN_VOC 39
#define SENSOR_CHAN_GAS_RES 40
#define SENSOR_CHAN_FLOW_RATE 41
#define SENSOR_CHAN_VOLUME 42
#define SENSOR_CHAN_VOLTAGE 43
#define SENSOR_CHAN_VSHUNT 44
#define SENSOR_CHAN_CURRENT 45
#define SENSOR_CHAN_POWER 46
#define SENSOR_CHAN_RESISTANCE 47
#define SENSOR_CHAN_ROTATION 48
#define SENSOR_CHAN_POS_DX 49
#define SENSOR_CHAN_POS_DY 50
#define SENSOR_CHAN_POS_DZ 51
#define SENSOR_CHAN_POS_DXYZ 52
#define SENSOR_CHAN_RPM 53
#define SENSOR_CHAN_FREQUENCY 54
#define SENSOR_CHAN_GAUGE_VOLTAGE 55
#define SENSOR_CHAN_GAUGE_AVG_CURRENT 56
#define SENSOR_CHAN_GAUGE_STDBY_CURRENT 57
#define SENSOR_CHAN_GAUGE_MAX_LOAD_CURRENT 58
#define SENSOR_CHAN_GAUGE_TEMP 59
#define SENSOR_CHAN_GAUGE_STATE_OF_CHARGE 60
#define SENSOR_CHAN_GAUGE_FULL_CHARGE_CAPACITY 61
#define SENSOR_CHAN_GAUGE_REMAINING_CHARGE_CAPACITY 62
#define SENSOR_CHAN_GAUGE_NOM_AVAIL_CAPACITY 63
#define SENSOR_CHAN_GAUGE_FULL_AVAIL_CAPACITY 64
#define SENSOR_CHAN_GAUGE_AVG_POWER 65
#define SENSOR_CHAN_GAUGE_STATE_OF_HEALTH 66
#define SENSOR_CHAN_GAUGE_TIME_TO_EMPTY 67
#define SENSOR_CHAN_GAUGE_TIME_TO_FULL 68
#define SENSOR_CHAN_GAUGE_CYCLE_COUNT 69
#define SENSOR_CHAN_GAUGE_DESIGN_VOLTAGE 70
#define SENSOR_CHAN_GAUGE_DESIRED_VOLTAGE 71
#define SENSOR_CHAN_GAUGE_DESIRED_CHARGING_CURRENT 72
#define SENSOR_CHAN_GAME_ROTATION_VECTOR 73
#define SENSOR_CHAN_GRAVITY_VECTOR 74
#define SENSOR_CHAN_GBIAS_XYZ 75
#define SENSOR_CHAN_ENCODER_COUNT 76
#define SENSOR_CHAN_ENCODER_REVOLUTIONS 77
#define SENSOR_CHAN_ALL 78
#define SENSOR_CHAN_COMMON_COUNT 79
#define SENSOR_CHAN_PRIV_START 79
#define SENSOR_CHAN_MAX 32767

#endif /* MESHBUS_INCLUDE_DT_BINDINGS_SENSOR_SENSOR_CHANNEL_H_ */
