# Peripherals
CONFIG_GPIO=y
CONFIG_INPUT=y

# Input
CONFIG_INPUT_GPIO_KEYS=y
CONFIG_INPUT_GPIO_QDEC=y
CONFIG_MBS_INPUT_BUTTON_MAX=10
# CONFIG_MFD=y
# CONFIG_MFD_TCA8418=y
# CONFIG_INPUT_TCA8418=y

# Power Management
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SHELL=y
CONFIG_POWER_DOMAIN=y
CONFIG_PM_DEVICE_POWER_DOMAIN=y
CONFIG_PM_DEVICE_RUNTIME_ASYNC=y
