#pragma once

#include "text/desktop_text.h"

/** Apps ID */
#define MESHBUS_DESKTOP_APP_ID_RADIO     "radio"
#define MESHBUS_DESKTOP_APP_ID_GNSS      "gnss"
#define MESHBUS_DESKTOP_APP_ID_MESHCORE  "meshcore"
#define MESHBUS_DESKTOP_APP_ID_MESSAGES  "messages"
#define MESHBUS_DESKTOP_APP_ID_NODES     "nodes"
#define MESHBUS_DESKTOP_APP_ID_SYSTEM    "system"

/** Apps name */
#define MESHBUS_DESKTOP_APP_NAME_RADIO     DESKTOP_TEXT_RADIO_TITLE
#define MESHBUS_DESKTOP_APP_NAME_GNSS      DESKTOP_TEXT_GNSS_TITLE
#define MESHBUS_DESKTOP_APP_NAME_MESHCORE  DESKTOP_TEXT_MESHCORE_TITLE
#define MESHBUS_DESKTOP_APP_NAME_MESSAGES  DESKTOP_TEXT_MESSAGES_TITLE
#define MESHBUS_DESKTOP_APP_NAME_NODES     DESKTOP_TEXT_NODES_TITLE
#define MESHBUS_DESKTOP_APP_NAME_SYSTEM    DESKTOP_TEXT_SYSTEM_TITLE

/** Apps menu index */
#define MESHBUS_DESKTOP_APP_MENU_INDEX_RADIO     1
#define MESHBUS_DESKTOP_APP_MENU_INDEX_GNSS      2
#define MESHBUS_DESKTOP_APP_MENU_INDEX_MESHCORE  3
#define MESHBUS_DESKTOP_APP_MENU_INDEX_MESSAGES  4
#define MESHBUS_DESKTOP_APP_MENU_INDEX_NODES     5
#define MESHBUS_DESKTOP_APP_MENU_INDEX_SYSTEM    9
